### ISSUE TITLE
Migrate to typescript

### ISSUE THREAD

**Issue by piecyk** [TanStack/virtual#221]

**Comment by tannerlinsley** [comment]
I would love this. If you want, you could steal my setup from https://github.com/tannerlinsley/react-virtual for the typescript+monorepo.

**Comment by piecyk** [comment]
Great, i will take a look, also link is point to this repo, did you had in mind https://github.com/tannerlinsley/react-location ?

**Comment by tannerlinsley** [comment]
Yep!

**Comment by tannerlinsley** [comment]
Done.
