### ISSUE TITLE
Incorrect rowVirtualizer virtualItems length

### ISSUE THREAD

**Issue by a2441918** [TanStack/virtual#250]
Hi, I am trying to render an array of objects inside Material-UI autocomplete and I am building up the virtualItems, but all I get is a length of 6 whatever I do. Please help on what I am doing wrong.

Here is the code.

https://stackblitz.com/edit/react-veeua8?file=src%2FApp.js

**Comment by a2441918** [comment]
@alinsimoc Thank you so much.

**Comment by aquibbaig** [comment]
I think that's not the case, even if I have around 1300 items, the items repeat on scroll no matter where I scroll to. (check the name)

https://user-images.githubusercontent.com/26324376/167372554-b75e0723-989b-48e5-b867-9d01428a411f.mov

My rowVirtualizer returns only 10 items, which gets repeated indefinitely.

Snippet:
```
```

**Comment by Intevel** [comment]
Facing the same Issue
