### ISSUE TITLE
Dynamic rows with children that change size post-render are not re-measured

### ISSUE THREAD

**Issue by khovansky-al** [TanStack/virtual#251]
Ran into an issue with images inside the dynamic rows.

Images are rendered as placeholders first. When the asset is loaded, the image component is re-rendered to correct dimensions. However, as the image component is a child of the virtual row, the row and the virtualizer are unaware of the size change.
This causes either a larger-than-intended gap between the elements, or an overlap.

I was able to mitigate it by
1. Saving the row container node (same that is attached to `measureRef`) to a separate ref.
2. Drilling down an `onLoad` callback prop
3. Calling `measureRef` manually with the node saved on step 1 inside `onLoad`.

It feels a bit cumbersome though. I wonder if this could be resolved inside the library, e.g. by having a resize observer on select nodes. In DIY testing of that idea without touching the library code though I ran into lots of re-rendering that decimated the performance.
I understand that maybe there is no good one-size-fits-all solution for this. In this case, maybe we could at least improve the ergonomics of re-measuring individual rows somehow.

Or maybe there is a way to handle this case already and I'm just unaware of it. `keyExtractor` doesn't seem to be the solution here because nothing about the row itself changes.

**Comment by khovansky-al** [comment]
Re-tried the resize observer solution. Attaching both observer and `measureRef` in a way that `measureRef` is always called first seems to resolve the performance issues. When scrolling and components are initially mounted, measuring happens directly through `measureRef` and observer callback no-ops. When a mounted component resizes, measurement is updated through the observer callback.

I guess this handling could be left to the implementation author, although we could add a warning and an example to the docs.

**Comment by uffou** [comment]
@khovansky-al can you share your code, I am having a similar case where everything is dynamically changing and need to handle all updates manually.

**Comment by piecyk** [comment]
Have a look at https://github.com/tannerlinsley/react-virtual/issues/28 there i explain bit more caveats with measureRef and using ResizeObserver.

**Comment by omgoshjosh** [comment]
I really like the following solution from @piecyk and would love to see it in this library somehow!

https://codesandbox.io/s/usevirtualresizeobserver-04-11-2021-75ye2?file=/src/useVirtual.tsx

it comes from somewhere in the little rabbit hole that @piecyk links ([here's another step in the rabbit hole](https://github.com/TanStack/react-virtual/issues/28#issuecomment-976457408))

[the codesandbox is from his other comment here](https://github.com/TanStack/react-virtual/discussions/212#discussioncomment-1587478)

the thing that gives me the most discomfort is having to write a wrapper "useVirtual" with a "import useVirtual as useVirtualImpl". but yeah if i ever have some time and energy i think i'd like to support this as some kind of opt-in behavior like much of the rest of how use-virtual is built.
