### ISSUE TITLE
scrollToIndex does not have a way to take paddingStart/paddingEnd or offsets into account

### ISSUE THREAD

**Issue by dantman** [TanStack/virtual#265]
useVirtual's paddingStart/paddingEnd can be used to make sticky headers work, e.g. table header sticky elements. However scrollToIndex doesn't take paddingStart/paddingEnd into account and doesn't have a way to specify start/end offsets and as a result when it scroll an item into view that item is hidden under the sticky header.

https://codesandbox.io/s/react-virtual-scrolltoindex-doesnt-work-with-sticky-headers-mrbhec?file=/src/main.jsx

I understand changing the behaviour of scrolling in regards to paddingStart/paddingEnd would be a breaking change. But perhaps the scroll function itself could have a offsetStart/offsetEnd.

**Comment by piecyk** [comment]
What if we would expose `getVirtualItem` metod, then we could do

```js
rowVirtualizer.scrollToOffset(getVirtualItem(10).start + paddingStart);
```

**Comment by dantman** [comment]
scrollToOffset also has some behaviour that needs to take padding into account.

e.g. It has a behaviour where if `align = undefined || 'auto'` and `toOffset` is after the bottom of the scroll area `align` will be set to `end`.

However that means something that is hidden under a floating footer beneath paddingEnd will end up with `align` set to `start` instead of `end`, even though to the user they'd be expecting it to show up at the end.

Also you'd probably need to pass `{ align: 'start' }` and do any alignment calculations yourself. Because if you also had a paddingBottom and left `align` as `auto` then when auto sets it to `end` your paddingBottom won't be taken into account. It'll also not be taken into account if you set `{ align: 'center' }`.

**Comment by tannerlinsley** [comment]
This is still not handled in the v3 beta but I would like it to be. Let's get some input here so we can fix it before we launch stable.

**Comment by dantman** [comment]
I've been using the `scrollPaddingStart` from #269 for awhile and it's been working.

**Comment by tannerlinsley** [comment]
Released!
