### ISSUE TITLE
Row height not updating with change in Viewport resize 

### ISSUE THREAD

**Issue by jkinley** [TanStack/virtual#273]
Am I doing something silly here? First time testing this library and so far its great. One thing I noticed is that the row heights don't seem to update until I scroll. Any ideas? Did I implement this incorrectly? Thanks for any help.

https://codesandbox.io/s/eager-kare-bpv3tb?file=/src/index.scss

**Comment by Amethystafyy282** [comment]
Did u take a look at here #251 
Im having problem with those too, especially when your estimation on each item is incorrect
Still waiting for version 3.0

**Comment by jkinley** [comment]
I will take a look at those other issues. Thank you.

**Comment by jkinley** [comment]
Also, do you know when 3.0 is suppose to drop?

**Comment by Amethystafyy282** [comment]
Been waiting for a long time haha, i really have no idea.

**Comment by piecyk** [comment]
> Also, do you know when 3.0 is suppose to drop?

I hope that it will happen soon 🙈 Didn't have too much time lately, but we need to take step back and re-thing some parts. Split them into smaller chunks, and deliver one by one. 

Current the bucket list for 3 starts to grow 
* migrate to typescript 
* limit the amount of re-renders 
* window scrolling 
* supporting react 18
* real dynamic list ( via resize observer )

**Comment by jkinley** [comment]
Thanks @piecyk for the update. That's really helpful. Cheers!

**Comment by The-Code-Monkey** [comment]
Yeah i've just implemented this in our app and when i resize the window to be bigger the row height doesnt change?

**Comment by The-Code-Monkey** [comment]
I've found that its the totalSize value that isnt updateing on window resize, the elements are but that value isnt.

**Comment by tannerlinsley** [comment]
We're tracking this internally with the new v3 beta. Closing for triage.
