### ISSUE TITLE
types: Interfaces are not exported

### ISSUE THREAD

**Issue by NicholasBoll** [TanStack/virtual#276]
Under some circumstances, not exporting interfaces can cause Typescript errors:

> Exported variable '[someVariable]' has or is using name 'ScrollToIndexOptions' from external module "./node_modules/react-virtual/types/index" but cannot be named.  `ts(4023)`

Adding `export` to these interfaces solves the problem:

```ts
export interface ScrollToOptions {
  align: ScrollAlignment
}

export interface ScrollToOffsetOptions extends ScrollToOptions {}
export interface ScrollToIndexOptions extends ScrollToOptions {}
```

This change could be forward merged to the `alpha` branch as well.

The other option is changing these interfaces to use `type` instead. If a `type` is used but not exported, Typescript will duplicate instead of naming them as symbols.

If a value uses `useVirtual` and is exported and definition files are required, the `ScrollToOffsetOptions` and `ScrollToIndexOptions` interfaces cannot be resolved and Typescript will throw an error.

## Reproduction sandbox
This Codesandbox demonstrates the error:
https://codesandbox.io/s/react-virtual-export-9syofm?file=/src/App.tsx:118-131

It is possible to work around this error by creating a type to manually map to the return type, but that is not possible with generic factory functions.

**Comment by tannerlinsley** [comment]
v3 beta solves this. Onward!

**Comment by NicholasBoll** [comment]
It does not look like v3 beta solves this issue: https://codesandbox.io/s/react-virtual-export-v3-4petj1?file=/src/App.tsx

The `ScrollToOptions` will still need to be exported.
