### ISSUE TITLE
Support RTL 

### ISSUE THREAD

**Issue by samiodeh1337** [TanStack/virtual#282]
Hi, I'm using react virtual grid columns and rows to build a table, when switching to RTL it doesn't render in opposite direction, I have solved this issue by changing the transformX to render from end to start, but the overscan for columns will leave the table empty on scrolling, the only way to solve it by making overscan a huge number to display all columns or they will disappear on scrolling, this makes the performecr so slow on rtl direction, any solution? Thanks

**Comment by samiodeh1337** [comment]
@piecyk @petersendidit @mogelbrod @oskarhane no support for RTL?

**Comment by tannerlinsley** [comment]
We'll try and fit this into v3.

**Comment by ndosarian** [comment]
As version 3 is released now, any improvements on this issue?

**Comment by ali-garajian** [comment]
@tannerlinsley still having trouble with rtl in horizontal mode. any plans on this?
