### ISSUE TITLE
scroll on the items stop after while on chrome 102 windows and linux

### ISSUE THREAD

**Issue by approximata** [TanStack/virtual#293]
scroll on the items stop after while on chrome 102 windows and linux.
If you scroll above the scrollable item (not next to them neither on the scroller) after few elements scroll stop. some sort of event fired at the items on the new chrome which stop the onscroll event. if you add to the css pointerEvents: "none" it is work fine. 
you can check on your samples: https://codesandbox.io/s/github/tannerlinsley/react-virtual/tree/main/examples/fixed

**Comment by tannerlinsley** [comment]
Does it happen here too?
> https://codesandbox.io/s/github/TanStack/virtual/tree/alpha/examples/react/fixed


Tanner Linsley

**Comment by approximata** [comment]
yep. same issue here. btw and almost all virtual-scroll solution.

**Comment by approximata** [comment]
https://crbug.com/1331231
