### ISSUE TITLE
Scroll stucks when having fixed overlay with pointer-events: none

### ISSUE THREAD

**Issue by ps73** [TanStack/virtual#313]
### Describe the bug

When using a fixed overlay with `pointer-events: none`  the scroll stucks in chromium based browsers.

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-9muacn?file=src%2FApp.tsx

### Steps to reproduce

1. Try scrolling in chromium based browser

### Expected behavior

1. Scrolling should be smooth

### Screenshots or Videos

https://user-images.githubusercontent.com/17291660/172569511-31e54430-8745-44ea-ae3c-3731dc93991b.mp4

### Platform

- OS: macOS
- Browser: Chrome, Edge, Brave and every other Chromium based Browser

### tanstack-virtual version

3.0.0-beta.2

### TypeScript version

latest

### Additional context

- Using the solid implementation

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ps73** [comment]
I have just checked it on a local Windows Machine (Chrome 102, Xeon, 16GB RAM) and it stucks with and without the overlay with `pointer-events: none`.

**Comment by simplylogicninjas** [comment]
The examples on Tanstack also stucks. On Windows, Chrome 102.0.5005.63

**Comment by ardeora** [comment]
https://codesandbox.io/s/mystifying-mayer-xxq3rv?file=/src/main.tsx Yeah I was able to replicate this. It definitely happens on React example as well. I'll take a look at this after work today. Thanks for pointing this out 😄

**Comment by ps73** [comment]
Also this is how it looks in Chromium v100. For me it is clear that it is a bug in latest chromium version.

https://user-images.githubusercontent.com/17291660/172660744-5113580a-cdb0-4535-a5d0-2c93b4996d79.mp4

**Comment by ps73** [comment]
A bug report already exists:
https://bugs.chromium.org/p/chromium/issues/detail?id=1332962

**Comment by ps73** [comment]
I have checked also Chrome Beta (103) and Chrome Canary (104).
In Beta the scroll stucks too. In Canary it seems that this is fixed. 
So maybe we have just have to wait until August 2nd.

**Comment by ps73** [comment]
Short update: I can confirm that this bug was fixed in latest Chrome Beta 103.0.5060.xx. which gets stable in 4 days on Jun 21st.

**Comment by jamesonhill** [comment]
Anyone else seeing this behavior after updating to chrome 107?

**Comment by ps73** [comment]
@jamesonhill Cannot confirm stucking. Checked it on macos with chrome version 107.0.5304.110

**Comment by jamesonhill** [comment]
> @jamesonhill Cannot confirm stucking. Checked it on macos with chrome version 107.0.5304.110
> 
> 
> 
> 

Disregard my comment. I had 1px overflow that caused similar behavior.
