### ISSUE TITLE
The axios dependency is missing in the infinite-scroll example

### ISSUE THREAD

**Issue by shervinchen** [TanStack/virtual#316]
### Describe the bug

The axios dependency is missing in the infinite-scroll example, so it run failed, please add it to package.json

### Your minimal, reproducible example

it's the example

### Steps to reproduce

yarn start, and failed

### Expected behavior

yarn start, successfully

### Platform

windows

### tanstack-virtual version

lastest version

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Added.
