### ISSUE TITLE
Latest version 3.0.0-beta.4 is not published to npm

### ISSUE THREAD

**Issue by zhouzi** [TanStack/virtual#325]
### Describe the bug

The `package.json`'s version of `packages/react-virtual` was bumped to `3.0.0-beta.4` but that version is not published to npm (the latest [version published to npm](https://www.npmjs.com/package/@tanstack/react-virtual) is `3.0.0-beta.2`).

### Your minimal, reproducible example

https://stackblitz.com/github/TanStack/virtual/tree/beta/examples/react/fixed

### Steps to reproduce

1. Clone a specific example
2. Install the dependencies
3. An error is raised as the version can't be found in the registry

### Expected behavior

I was expecting the versions referenced in the examples to be published.

### How often does this bug happen?

Every time

### Platform

- OS: MacOS
- Browser: Brave

### tanstack-virtual version

3.0.0-beta.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sag1v** [comment]
I was going nuts with the inconsistency between the DOCS and the actual versions that are published.

For other reader:

If you get

> scrolltoindex is not a function

You need version `3.0.0-beta.4`, which is **not published** as mentioned in this issue.

@tannerlinsley Are you still actively working on this repo?

**Comment by zhouzi** [comment]
> For other reader:
> 
> If you get
> 
> > scrolltoindex is not a function
> 
> You need version `3.0.0-beta.4`, which is **not published** as mentioned in this issue.)

I think you are having a different issue. We use `3.0.0-beta.2` and `scrollToIndex` is available.

**Comment by sag1v** [comment]
> > For other reader:
> > 
> > If you get
> > 
> > > scrolltoindex is not a function
> > 
> > You need version `3.0.0-beta.4`, which is **not published** as mentioned in this issue.)
> 
> I think you are having a different issue. We use `3.0.0-beta.2` and `scrollToIndex` is available.

Interesting 🤔 i will check. Thanks 🙏

**Comment by KosGrillis** [comment]
bump, can we expect this to be released to NPM?

**Comment by tannerlinsley** [comment]
Making some new releases now. Thanks for your patience!
