### ISSUE TITLE
No Type Intellisense or Type Imports available when importing from @tanstack/react-virtual

### ISSUE THREAD

**Issue by KevinVandy** [TanStack/virtual#336]
### Describe the bug

It appears that types are not exported from `@tanstack/react-virtual`.

`const rowVirtualizer = useVirtualizer({...})` yields a type of `any` and no intellisense or autocomplete is present to give hints on the props that are available.

Also from looking at the source code, it appears that VirtualizerOptions should be a type that is exported and available to be imported, but trying to import it results in an error.

```ts
import type { VirtualizerOptions } from '@tanstack/react-virtual';
```

`Module '"@tanstack/react-virtual"' declares 'VirtualizerOptions' locally, but it is not exported.ts (2459)`

Attached below are screenshots showing the errors, but this behavior can be seen in the default code sandbox examples too.

### Your minimal, reproducible example

https://tanstack.com/virtual/v3/docs/examples/react/fixed

### Steps to reproduce

Problem 1: 
```js
import { useVirtualizer } from '@tanstack/react-virtual';

const rowVirtualizer = useVirtualizer({...}) //rowVirtualizer is of `any` type
```

Problem 2:

`import type { VirtualizerOptions } from '@tanstack/react-virtual';`

Type is not available

### Expected behavior

Types should be available and able to be imported as they are exported from the index.ts of the lib.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="832" alt="image" src="https://user-images.githubusercontent.com/28243511/177240167-0d33e7b9-efaf-4232-85da-da6963444a70.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/28243511/177240097-0906cada-132d-439b-bd39-95df84047f34.png">

### Platform

CodeSandbox MacOs

### tanstack-virtual version

3.0.0-beta.2

### TypeScript version

v4.7.4

### Additional context

I specifically want to be able to have access to re-export `VirtualizerOptions` in order to be able to provide that type from another NPM library that is letting a dev pass in their own virtualizer props in a type-safe way

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by zhouzi** [comment]
Also reported in #326

**Comment by tannerlinsley** [comment]
Duplicate.
