### ISSUE TITLE
TypeScript error about missing @tanstack/virtual-core unless you enable skipLibCheck

### ISSUE THREAD

**Issue by dumbmatter** [TanStack/virtual#339]
### Describe the bug

I get this TypeScript error when using @tanstack/react-virtual unless I enable the "skipLibCheck" option in tsconfig:

```$ tsc
node_modules/@tanstack/react-virtual/build/types/react-virtual/src/index.d.ts:1:62 - error TS2307: Cannot find module '@tanstack/virtual-core' or its corresponding type declarations.

1 import { PartialKeys, Virtualizer, VirtualizerOptions } from '@tanstack/virtual-core';
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tanstack/react-virtual/build/types/react-virtual/src/index.d.ts:2:15 - error TS2307: Cannot find module '@tanstack/virtual-core' or its corresponding type declarations.

2 export * from '@tanstack/virtual-core';
                ~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@tanstack/react-virtual/build/types/react-virtual/src/index.d.ts:1
```

### Your minimal, reproducible example

https://github.com/dumbmatter/tanstack-virtual-typescript

### Steps to reproduce

1. Clone repo
2. `npm install`
3. `npm run tsc`
4. Observe error
5. Uncomment the skipLibCheck line in tsconfig.json
6. `npm run tsc`
7. Observe no error

### Expected behavior

There should not be an error when you run TypeScript.

### How often does this bug happen?

Every time

### Platform

Node v18.4 on Linux

### tanstack-virtual version

@tanstack/react-virtual v3.0.0-beta.2

### TypeScript version

v4.7.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed in the latest release.
