### ISSUE TITLE
Documentation says "You should call this function when:" and ends there

### ISSUE THREAD

**Issue by hangtwenty** [TanStack/virtual#341]
### Describe the bug

In the docs there's this phrase:

> You should call this function when:

but the document ends there.

https://github.com/TanStack/virtual/blob/b750b75f963e9e2f90c6fad595fda4117dd2acef/docs/api/virtualizer.md?plain=1#L248

### Your minimal, reproducible example

https://github.com/TanStack/virtual/blob/b750b75f963e9e2f90c6fad595fda4117dd2acef/docs/api/virtualizer.md?plain=1#L248

### Steps to reproduce

N/A

### Expected behavior

N/A

### Platform

N/A

### tanstack-virtual version

v3.0.0-beta.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Fixed!
