### ISSUE TITLE
Window scrolling is delayed, bounces and miss-positioned

### ISSUE THREAD

**Issue by AndyOGo** [TanStack/virtual#344]
### Describe the bug

First these headless components are great.

I'm using the [`useWindowVirtualizer`](https://tanstack.com/virtual/v3/docs/adapters/react-virtual#usewindowvirtualizer) react hook adapter.

Unfortunately the measurements are incorrect, they bounce and the table updates delayed not in sync with the scroll.

The table does not cover the whole screen.
So it should be observed to for being visible within the viewport, that is not done as far as I can tell.

### Your minimal, reproducible example

http://example.com

### Steps to reproduce

Sorry, closed source

### Expected behavior

Tables should be in Sync with the window scroll bar, as far as they are within the visible viewport of the HTML documemnt.

### How often does this bug happen?

Every time

### Platform

- OS: Windows
- Browsers: Edge Version 102.0.1245.56 (Official build) (64-bit)

### tanstack-virtual version

v3.0.0-beta.13

### TypeScript version

v4.5.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
To help triage a lot of outdated issues, we're closing this due to its age. If this issue is still relevant, please tag @ tannerlinsley in a new comment confirming the case.
