### ISSUE TITLE
Scroll position not synced with actual position

### ISSUE THREAD

**Issue by nonua** [TanStack/virtual#345]
### Describe the bug

Probably related to #344 

The scroll position with dynamic height rows shifts when scrolling up and down, it is out of sync with the actual position

### Your minimal, reproducible example

https://codesandbox.io/s/nkpe0m

### Steps to reproduce

Scroll the first list up and down

### Expected behavior

The scroll position should be synced

### How often does this bug happen?

Every time

### Platform

Windows 10 and Chrome browser but it is irrelevant to the issue

### tanstack-virtual version

3.0.0-beta.13

### Additional context

It's a bit of a bummer that this is happening because the purpose of TanStack/virtual is remarkable, this is the only reason why I would not use this package yet, instead I'll stick with slower [react-virtualized](https://github.com/bvaughn/react-virtualized) or even [react-window](https://github.com/bvaughn/react-window) that do not have this problem

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by jampy** [comment]
@nonua are *dynamic* heights possible with [react-virtualized](https://github.com/bvaughn/react-virtualized)? How?

**Comment by nonua** [comment]
@jampy With `CellMeasurerCache` and [CellMeasurer API](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md)

**Comment by jampy** [comment]
@nonua ok, thanks

Did you find a solution for the problem described in this issue? I'm facing the same problem.

**Comment by piecyk** [comment]
Should be fixed in latest beta.

**Comment by nonua** [comment]
Hi @piecyk , I just checked this out for dynamic heights and it still does that unfortunetly  
![2023-01-06_19h50m22s](https://user-images.githubusercontent.com/77514325/211079049-e38b578a-eb28-413f-9c60-ecbdcd2bbd0a.gif)



Whereas it does not happen with fixed/variable heights
![2023-01-06_19h48m27s](https://user-images.githubusercontent.com/77514325/211078821-fb431401-edbe-4442-9470-2c0db0d7d4f4.gif)

**Comment by piecyk** [comment]
Hi @nonua there are two issues here, first is the white space when dragging, basic it's the limitation of browser how fast it can render. Another issues is the scroll handle when scrolling, reported #421 interesting is that it's not happening in Firefox and Safari.
