### ISSUE TITLE
Hook interface does not expose measureSize option

### ISSUE THREAD

**Issue by gmltA** [TanStack/virtual#347]
### Describe the bug

There's currently no possibility to override `measureSize` function in `useVirtual` hook options object in TypeScript.

According to library sources, the hook expects `measureSize` as an argument and handles it properly.

https://github.com/TanStack/virtual/blob/5300e47ea5ea4084b3a54a0fcd679c8a9653f131/src/index.js#L42

But this is not reflected in library typings.

### Expected behavior

Types to be consistent with actual implementation.

### tanstack-virtual version

2.10.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
Please try 3.0 beta and let me know if the issue persists.

**Comment by gmltA** [comment]
@tannerlinsley I saw that there is an interface in v3 for this, but since it is still in beta, it makes sense to support currently stable version, doesn't it?

**Comment by tannerlinsley** [comment]
3.0 is the answer. Please upgrade.
