### ISSUE TITLE
`scrollToFn()` is called twice when using `scrollToIndex()` or `scrollToOffset()`

### ISSUE THREAD

**Issue by christiankaindl** [TanStack/virtual#351]
### Describe the bug

When a custom `scrollToFn()` function is provided in the options to `useVirtualizer()`, it is called twice with every call to `scrollToIndex()` or `scrollToOffset()`. 

### Your minimal, reproducible example

https://codesandbox.io/s/react-virtual-bug-repro-4dz5ec?file=/src/App.js

### Steps to reproduce

1. Click on the button "Scroll to random index"
2. Observe in the console that `scrollToFn()` was executed twice
 

### Expected behavior

`scrollToFn()` should only be called once.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="337" alt="Screen Shot 2022-07-29 at 17 13 41" src="https://user-images.githubusercontent.com/15364860/181793860-5b5f789a-ed28-4a3f-a9f2-88cf14fe4c7d.png">

### Platform

macOS 12.4

Tested/Reproduced on latest Firefox and Safari

### tanstack-virtual version

3.0.0-beta.13

### TypeScript version

4.5.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by christiankaindl** [comment]
After some debugging, these lines are the culprit:
https://github.com/TanStack/virtual/blob/6c3d6ca7f53d2b286791effea1b09fe307b0373d/packages/virtual-core/src/index.ts#L517-L520

A comment on an earlier commit that changed this line describes the reasoning as 
>

**Comment by tannerlinsley** [comment]
Open a PR to remove the animation frame and I’ll merge to beta

**Comment by christiankaindl** [comment]
@tannerlinsley -> https://github.com/TanStack/virtual/pull/355
