### ISSUE TITLE
Excessive re-renders when scrolling

### ISSUE THREAD

**Issue by christiankaindl** [TanStack/virtual#352]
### Describe the bug

Scrolling a virtualized list seems to cause a 2+ re-renders on every scroll event. In the linked Sandbox, up to 90 re-renders are triggered before any items are added or removed from the virtual list.

Possibly related
- https://github.com/TanStack/virtual/discussions/212
- https://github.com/TanStack/virtual/discussions/331

Example of react-virtual 2.8, which does not have this problem: https://codesandbox.io/s/react-virtual-2-8-no-re-renders-xlmned

I would love to help debug the issue, but aren't that experienced with monorepo setups yet. Any guidance is appreciated :)

### Your minimal, reproducible example

https://codesandbox.io/s/react-virtual-excessive-re-renders-iqtyuf?file=/src/App.js

### Steps to reproduce

1. Scroll the list continuously (e.g. with a trackpad) or use the button "Scroll 1 row"
2. Observe the console.log's in the console, lots of re-renders are logged

### Expected behavior

I would expect to only see re-renders when items are added or removed from the virtualized list. 

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/15364860/181839191-ef0c4465-fd77-434a-b8a8-6f0eedb84b6d.mov

### Platform

macOS 12.4

Tested on latest Firefox and Safari

### tanstack-virtual version

3.0.0-beta.13

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by wuarmin** [comment]
Fixing this would be awesome!

**Comment by christiankaindl** [comment]
Managed to set up the project locally and did some debugging. The reason for the many re-renders is that somewhere the memoization is invalidated on every scroll event.

First, `scrollOffset` is set on every scroll event here:
https://github.com/TanStack/virtual/blob/6c3d6ca7f53d2b286791effea1b09fe307b0373d/packages/virtual-core/src/index.ts#L336-L339

which is then used as a memoization key to `calculateRange()`
https://github.com/TanStack/virtual/blob/6c3d6ca7f53d2b286791effea1b09fe307b0373d/packages/virtual-core/src/index.ts#L388

That would not be a problem in and of itself, the issue is that `calculateRange()` always returns a new object so that the memoization of `getIndexes()` is invalidated, and then `getVirtualIems()` as well. So I think a fix would consist of making sure that `calculateRange()` returns the same object when the range is the same.

**Comment by christiankaindl** [comment]
I was wrong. Well, kinda... the memoization indeed wasn't working, but that wasn't the cause for the React re-renders :D found the root cause now and fixed it locally. Will submit a MR shortly!

The issue is with line 338, which calls the `onChange` callback for _every scroll event_ (disguised as `this.notify()` here).
https://github.com/TanStack/virtual/blob/6c3d6ca7f53d2b286791effea1b09fe307b0373d/packages/virtual-core/src/index.ts#L336-L339

That handler is then used in the react-virtual adapter to trigger re-renders:
https://github.com/TanStack/virtual/blob/5f0dfe9da00841d6a686d9dce5c611facdeb175a/packages/react-virtual/src/index.tsx#L27-L30

The fix in my opinion is to only call `onChange()` handler when the range of the rendered items changes, not on every scroll event.
