### ISSUE TITLE
Dynamically updating count seems to not trigger an update

### ISSUE THREAD

**Issue by wuarmin** [TanStack/virtual#363]
### Describe the bug

When `dataCount` changes from 0 to 1000, the list is not updated.
```javascript
const rowVirtualizer = useVirtualizer({
  count: dataCount,
  getScrollElement: () => tableContainer.current,
  estimateSize: () => 21,
  overscan: 5
});
```

### Your minimal, reproducible example

https://codesandbox.io/s/react-virtual-only-one-item-is-rendered-at-first-bfoj5r?file=/src/main.tsx

### Steps to reproduce

Checkout following sandbox:
https://codesandbox.io/s/react-virtual-only-one-item-is-rendered-at-first-bfoj5r?file=/src/main.tsx
At first glance only one row will be visible. This is because on first render `dataCount` is 0, but then it changes to 1000, but the list is not updated.

### Expected behavior

All items, which fit in the `tableContainer`, should be rendered.

### How often does this bug happen?

Every time

### Platform

-OS Linux Ubuntu Browser: Firefox 103.0b9 (64-bit)

### tanstack-virtual version

3.0.0-beta.14

### Additional context

#353 

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Himself65** [comment]
Same error here

**Comment by Himself65** [comment]
[v3.0.0-beta.9](https://github.com/TanStack/virtual/releases/tag/v3.0.0-beta.9) runs good

**Comment by wuarmin** [comment]
@christiankaindl Do you have a hint about the way to fix this?

**Comment by christiankaindl** [comment]
Yes, you need to re-calculate the virtual item range in `setOptions()`, which is defined here:
https://github.com/TanStack/virtual/blob/f4698d85f33b4a62ca949c0c2dfa0c05c8ed0f4a/packages/virtual-core/src/index.ts#L286

So call `this.calculateRange()` at the end of `setOptions()`. Tested this locally and it seems to work nicely, will open a PR shortly :)

**Comment by christiankaindl** [comment]
@wuarmin I think this PR should fix your issue -> #366

**Comment by christiankaindl** [comment]
I don't know if that's intentional, but the PR in #366 was not merged yet

**Comment by SvetaSR** [comment]
Hi, any updates for this issue? :( I really don't like that we have to use a workaround.

**Comment by coycoylaniba** [comment]
any update of this issue?

**Comment by rodygossetmnhn** [comment]
Any updates on this still ?

**Comment by abbeyperini** [comment]
The closed PR says the issue was resolved by PR #414, but I'm still running into this in `@tanstack/vue-virtual 3.13.12`

**Comment by piecyk** [comment]
@abbeyperini Thanks for the update! PR should #414 fixed the core case, but it looks like Vue Virtual might still be hitting by this. If you’re open to it, a small repro or any clues you found would really help us track it down, and happy to collaborate on a fix if you’re interested.

**Comment by dalechyn** [comment]
> [@abbeyperini](https://github.com/abbeyperini) Thanks for the update! PR should [#414](https://github.com/TanStack/virtual/pull/414) fixed the core case, but it looks like Vue Virtual might still be hitting by this. If you’re open to it, a small repro or any clues you found would really help us track it down, and happy to collaborate on a fix if you’re interested.

Running into this in React with version `@tanstack/react-virtual@^3.0.0-beta.68` and `3.13.9`

**Comment by evankford** [comment]
@abbeyperini For `vue`, there is a way to trigger an update by assigning options to a ref and then reassigning the options ref value when needed.. 

````ts
const options = ref({
  count: listThatChanges.value.length,
  estimateSize: () => 50,
  getScrollElement: () => parentRef.value,
})

//By default, this will not change when the list does.
const rowVirtualizer = useVirtualizer(options)

//This does not work:
watch(()=>listThatChanges.value.length, (newLength) => {
  rowVirtualizer.value.setOptions((prev) => ({
    ...prev,
    count: newLength,
  }))
})

// This works:
watch(()=>listThatChanges.value.length, (v) => {
  options.value.count  = v
})
````
You can also use a computed object:
````ts
const options = computed( ()=>({
  count: listThatChanges.value.length,
  estimateSize: () => 90,
  getScrollElement: () => parentRef.value
}))
const rowVirtualizer = useVirtualizer(options)
````

The clunkiness has a point it seems: all the "reactivity" of the virtualizer comes from watching the `options` object. We can't update anything inside the rowVirtualizer, really, because it's a `shallowRef` of the core virtualizer, so the core will never see the updates to member variables that we make.

@piecyk It feels like count reactivity should be covered in the docs, is there a way for me to help with that?
