### ISSUE TITLE
Scroll restoration doesn't work when using useWindowVirtualizer

### ISSUE THREAD

**Issue by meotimdihia** [TanStack/virtual#378]
### Describe the bug

Scroll restoration doesn't work when using `useWindowVirtualizer`.

I used `react-virtualized` and it works fine.

### Your minimal, reproducible example

https://stackblitz.com/edit/next-typescript-pokptk-mucmhs?file=pages%2FanotherPage.tsx,pages%2Findex.tsx

### Steps to reproduce

1. scroll down
2. click any link
3. click to go back.

### Expected behavior

The scroll position is restored.

### How often does this bug happen?

Every time

### Platform

Chrome

### tanstack-virtual version

@tanstack/react-virtual@^3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by meotimdihia** [comment]
I ended up restoring the scroll position manually.

**Comment by milad1367** [comment]
@meotimdihia How did you fix this problem? because when you get the previous scroll position from local storage  you need something like offset prop and not initialOffset! 
can you describe it, please?

**Comment by meotimdihia** [comment]
This is my code while using next.js
I saved the position when users scroll.

```ts
import { useRouter } from "next/router"
import useMounted from "@libs/use_mounted"
import { useCallback, useEffect } from "react"
import { useScroll } from "@use-gesture/react"

export default function useRestoration({
  minHeight = null,
  conditinal = true,
  virtual = null
}: {
  virtual?: any
  minHeight?: number
  conditinal?: boolean
}) {
  const mounted = useMounted()
  const router = useRouter()
  const key = "myapp-scroll-restoration-" + router.pathname

  // useScrollRestoration(router)
  const scrollToLastPosition = useCallback(() => {
    try {
      const pos = sessionStorage.getItem(key)
      if (pos) {
        const parsedPos = JSON.parse(pos)

        if (
          document.body.scrollHeight > parsedPos.y &&
          (!minHeight || minHeight < document.body.scrollHeight) &&
          (-1 > window.scrollY - parsedPos.y ||
            window.scrollY - parsedPos.y > 0)
        ) {
          window.scrollTo(parsedPos.x, parsedPos.y)

          if (virtual) {
            virtual.scrollToOffset(parsedPos.y)
          }
          try {
            sessionStorage.removeItem(key)
          } catch (e) {
            console.error(e)
          }
        }
      }
    } catch (e) {
      console.error(e)
    }
  }, [key, minHeight, virtual])

  if (mounted && conditinal) {
    scrollToLastPosition()
  }
  function getPosition(): number {
    try {
      const pos = sessionStorage.getItem(key)
      if (pos) {
        const parsedPos = JSON.parse(pos)
        // sessionStorage.removeItem(key)

        return parsedPos.y
      }
      return 0
    } catch (e) {
      return 0
    }
  }

  const savePostion = useCallback(() => {
    const x = window.scrollX
    const y = window.scrollY
    try {
      const position = sessionStorage.getItem(key)
      if (!position) {
        sessionStorage.setItem(key, JSON.stringify({ x, y }))
      } else if (position) {
        if (y != 0) {
          sessionStorage.setItem(key, JSON.stringify({ x, y }))
        }
      }
    } catch (e) {
      console.error(e)
    }
  }, [key])
  useEffect(() => {
    if (conditinal) scrollToLastPosition()

    // router.events.on("routeChangeStart", savePostion)
    // // window.addEventListener("mousedown", savePostion)
    // return () => router.events.off("routeChangeStart", savePostion)
  }, [conditinal, scrollToLastPosition])
  useScroll(
    () => {
      savePostion()
    },
    { target: window, axis: "y", threshold: 10 }
  )
  return [scrollToLastPosition, getPosition]
}

```

**Comment by meotimdihia** [comment]
But I recommend you should try this package first:

https://github.com/petyosi/react-virtuoso

It is better in my opinion. Though it is not perfect too.

**Comment by piecyk** [comment]
In latest beta virtualizer expose `scrollOffset` this can be save to storage, then restore it via `initialOffset`. In dynamic case we can also store `measurementsCache`  and restore it via `initialMeasurementsCache`

**Comment by milad1367** [comment]
@piecyk Can you write an example in fixed mode, please?

**Comment by piecyk** [comment]
> @piecyk Can you write an example in fixed mode, please?

@milad1367 something like this https://codesandbox.io/s/busy-haslett-9t6yge?file=/pages/index.js

**Comment by milad1367** [comment]
> 

Thank you so much,

**Comment by milad1367** [comment]
@piecyk 
My current code :

```
import useGetData from "@/pages/api/useGetData";
import { useRouter } from "next/router";
import { useVirtualizer, observeWindowOffset } from "@tanstack/react-virtual";
import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useDebounce, useSessionStorage } from "usehooks-ts";

export function ProductList() {
  const { query } = useRouter();
  const { search, select } = query;

  const filter = select?.toString().split("-");
  const parentRef = React.useRef(null);
  const [value, setValue] = useSessionStorage("virtualizer_scrollOffset", 0);
  const { data, isLoading, isError } = useGetData(search?.toString(), filter); //TODO think about better option search?.toString()
  const [scrollY, setScrollY] = useState(0);
  const debouncedScrollPosition = useDebounce(scrollY, 1000); // TODO

  useEffect(() => {
    setValue(debouncedScrollPosition);
  }, [debouncedScrollPosition, setValue]);

  const rowVirtualizer = useVirtualizer({
    count: data?.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 35,
    initialOffset: (() => {
      if (typeof sessionStorage !== "undefined") {
        return parseInt(
          sessionStorage.getItem("virtualizer_scrollOffset") || ""
        );
      }
      return 0;
    })(),
  });
  const onScroll = (e: any) => {
    setScrollY(e.target.scrollTop);
  };

  if (isLoading) {
    return <div>is loading ...</div>;
  }
  if (isError) {
    return <div>Error!</div>;
  }

  return (
    <>
      <div
        style={{
          height: `400px`,
          overflow: "auto", // Make it scroll!
        }}
        ref={parentRef}
        onScroll={onScroll}
      >
        <div
          style={{
            height: `${rowVirtualizer.getTotalSize()}px`,
            width: "100%",
            position: "relative",
          }}
        >
          {rowVirtualizer.getVirtualItems().map((virtualRow) => (
            <div
              key={virtualRow.index}
              className={virtualRow.index % 2 ? "ListItemOdd" : "ListItemEven"}
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: `${data[virtualRow.index]}px`,
                transform: `translateY(${virtualRow.start}px)`,
              }}
            >
              <Link href={`/product/${data[virtualRow.index].id}`}>
                {data[virtualRow.index].id}- {data[virtualRow.index].title}
              </Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

```
![Screen Shot 2023-01-18 at 00 53 21](https://user-images.githubusercontent.com/15375991/213015220-fd8d0e2d-60b3-4c03-91d8-7a6de53a42be.png)

now when I add observeElementOffset:
```
import useGetData from "@/pages/api/useGetData";
import { useRouter } from "next/router";
import { useVirtualizer, observeWindowOffset } from "@tanstack/react-virtual";
import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useDebounce, useSessionStorage } from "usehooks-ts";

export function ProductList() {
  const { query } = useRouter();
  const { search, select } = query;

  const filter = select?.toString().split("-");
  const parentRef = React.useRef(null);
  const [value, setValue] = useSessionStorage("virtualizer_scrollOffset", 0);
  const { data, isLoading, isError } = useGetData(search?.toString(), filter); //TODO think about better option search?.toString()
  const [scrollY, setScrollY] = useState(0);
  const debouncedScrollPosition = useDebounce(scrollY, 1000); // TODO

  useEffect(() => {
    setValue(debouncedScrollPosition);
  }, [debouncedScrollPosition, setValue]);

  const rowVirtualizer = useVirtualizer({
    count: data?.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 35,
    initialOffset: (() => {
      if (typeof sessionStorage !== "undefined") {
        return parseInt(
          sessionStorage.getItem("virtualizer_scrollOffset") || ""
        );
      }
      return 0;
    })(),
    observeElementOffset: (instance, cb) => {
      return observeWindowOffset(instance, (offset) => {
        if (typeof sessionStorage !== "undefined") {
          sessionStorage.setItem(
            "virtualizer_scrollOffset",
            offset?.toString()
          );
        }
        cb(offset);
      });
    },
  });
  const onScroll = (e: any) => {
    setScrollY(e.target.scrollTop);
  };

  if (isLoading) {
    return <div>is loading ...</div>;
  }
  if (isError) {
    return <div>Error!</div>;
  }

  return (
    <>
      <div
        style={{
          height: `400px`,
          overflow: "auto", // Make it scroll!
        }}
        ref={parentRef}
        onScroll={onScroll}
      >
        <div
          style={{
            height: `${rowVirtualizer.getTotalSize()}px`,
            width: "100%",
            position: "relative",
          }}
        >
          {rowVirtualizer.getVirtualItems().map((virtualRow) => (
            <div
              key={virtualRow.index}
              className={virtualRow.index % 2 ? "ListItemOdd" : "ListItemEven"}
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                width: "100%",
                height: `${data[virtualRow.index]}px`,
                transform: `translateY(${virtualRow.start}px)`,
              }}
            >
              <Link href={`/product/${data[virtualRow.index].id}`}>
                {data[virtualRow.index].id}- {data[virtualRow.index].title}
              </Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
```

![Screen Shot 2023-01-18 at 00 56 42](https://user-images.githubusercontent.com/15375991/213015712-fa808d72-af6f-4dd2-8749-7d964f20d0c2.png)
I don't know what's wrong!
I'm using Nextjs.

**Comment by Ugikie** [comment]
> > @piecyk Can you write an example in fixed mode, please?
> 
> @milad1367 something like this https://codesandbox.io/s/busy-haslett-9t6yge?file=/pages/index.js

I'm trying to get this to work with just `useVirtualizer` instead of `useWindowVirtualizer` but for some reason every time I return back from the 2nd page, it starts the offset back at 0. If I refresh the page before going back, then it starts at exactly 1250 every time... even though the value I have stored in localStorage for the last recorded offset is ~5000... I can't figure out why it is resetting to 0 when going back, and why it is using specifically 1250 every time when going back after a refresh.

I think the fact that it is using 0 when going back without refreshing is somehow due to the `initialOffset` only being applied on init when calling the constructor for the first time... when I navigate to another page and then return, something tells me that it is not taking my `initialOffset` value correctly...

Could you or someone please provide an update exactly with how to do this properly using `useVirtualizer`?

Thanks so much!

**Comment by piecyk** [comment]
> The data I am displaying is dynamic

@Ugikie that is the case, basic when scroll is restored, virtualizer don't remember prev read sizes and auto adjustment kiks in, you also need to store `measurementsCache` and restore it by passing via initialMeasurementsCache.

for example you can save it on click 

```tsx
onClick={() => {
  initialOffset = virtualizer.scrollOffset;
  initialMeasurementsCache = virtualizer.measurementsCache;
}}
```

**Comment by piecyk** [comment]
@Ugikie or even better you can save it on effect cleanup, checkout this react-router basic example https://stackblitz.com/edit/github-trynzk

**Comment by nuschk** [comment]
I've just stumbled over this issue. I'm using tanstack-router and it doesn't seem to be solved between these two packages.

For those interested, my resulting, simple, solution is to use the history's state API. I like it because I don't have to worry about the scroll restoration being triggered by the wrong screen. Also, no ids!

```tsx
  // Read from the history state
  const {
    vtableItemCount: restoreItemCount,
    vtableOffset: restoreOffset,
    vtableMeasureCache: restoreMeasurementsCache,
  } = history.state;

  const virtualizer = useWindowVirtualizer({
    // itemCount is undefined in my case, until the API resolves.
    count: itemCount == undefined ? restoreItemCount : itemCount,
    // Restore the offset and also the measurements cache (when measuring, not required otherwise) 
    initialOffset: restoreOffset,
    initialMeasurementsCache: restoreMeasurementsCache,
  });

  // Update scrollpos and item count for scroll restoration.
  const scrollPos = useDebounce(useWindowScroll()[0].y, 500);
  React.useEffect(() => {
    history.replaceState(
      {
        vtableItemCount: itemCount,
        vtableOffset: scrollPos,
        vtableMeasureCache: virtualizer.measurementsCache,
      },
      document.title,
      window.location.href,
    );
  }, [itemCount, scrollPos, virtualizer.measurementsCache]);
```

Works perfectly!

**Comment by piecyk** [comment]
@nuschk great! Thanks for the comment.

**Comment by glassworks-projects** [comment]
I have been trying this (but saving my scroll info in a state store using Zustand instead of history or whatever), and it full on doesn't work. `useWindowVirtualizer` will _sometimes_ just ignore `initialOffset` when it's passed. And I can't figure out any sort of deterministic explanation for when it will honor `initialOffset` and when it won't.

Here's some code; I've confirmed via print debugging that the scroll state is being saved and loaded appropriately, but the virtualizer will then just ignore it, except when it doesn't. 

```typescript 

// scroll store implementation
import { VirtualItem } from "@tanstack/react-virtual";
import { create } from "zustand";

type ScrollState = {
  [route: string]: {
    offset: number;
    count: number;
    measurementsCache: VirtualItem[];
  };
};

type ScrollStore = {
  feeds: ScrollState;
  setScrollState: (route: string, state: ScrollState[string]) => void;
};

export const useScrollStore = create<ScrollStore>((set) => ({
  feeds: {},
  setScrollState: (route, state) =>
    set((store) => ({ feeds: { ...store.feeds, [route]: state } })),
}));

// used in exported components
const useVirtual = ({
  options,
  from,
  count,
}: {
  options: Omit<Parameters<typeof useWindowVirtualizer>[number], "count">;
  from: string;
  count: number;
}) => {
  const { feeds, setScrollState } = useScrollStore();
  const feedState = feeds[from];
  const location = useLocation();
  const navigation = useNavigation();

  const virtualizer = useWindowVirtualizer({
    ...options,
    count: feedState?.count ?? count,
    initialMeasurementsCache: feedState?.measurementsCache,
    initialOffset: feedState?.offset,
  });

  useEffect(() => {
    const isNavigatingAway =
      location.pathname === from && navigation.state !== "idle";
    if (isNavigatingAway) {
      setScrollState(from, {
        offset: virtualizer.scrollOffset ?? 0,
        count,
        measurementsCache: virtualizer.measurementsCache,
      });
    }
  }, [
    from,
    virtualizer.scrollOffset,
    virtualizer.measurementsCache,
    setScrollState,
    count,
    location,
    navigation,
  ]);

  return virtualizer;
};
```

**Comment by piecyk** [comment]
@glassworks-projects this is the part what it's checking the initialOffset, basic when scrollOffset is null, https://github.com/TanStack/virtual/blob/main/packages/virtual-core/src/index.ts#L537-L541

**Comment by vipul-nema** [comment]
@piecyk  - Thanks your suggetion working very smooth now,  But it think should/can be handle at library level itself .
We faced same issue in our next 16 app router + react-virtualize + react-query setup, 

**Our use case- infinite scroll + window level scroll + dynamic heights + back scroll position persistance** 

The Flow - The key to this working is the Lifecycle of the Hook:
- Mount: It checks sessionStorage and "pre-loads" the Virtualizer so it doesn't start at index 0.
- Unmount: Right before the component disappears (e.g., when clicking a link), it takes a "snapshot" of the current scroll position and the measured heights of the items.

// lib/scroll-cache.ts



`


    export const saveScrollState = (offset: number, cache: any, key: string) => {
      if (typeof window === "undefined") return;
      sessionStorage.setItem(key, JSON.stringify({ offset, cache }));
    };
    
    
    export const getCachedScrollState = (key: string) => {
      if (typeof window === "undefined") return { initialOffset: 0, measurementsCache: undefined };
      const saved = sessionStorage.getItem(key);
      return saved ? JSON.parse(saved) : { initialOffset: 0, measurementsCache: undefined };
    };


`

**The Implementation Logic**

`

    "use client";
    
    import { useWindowVirtualizer } from "@tanstack/react-virtual";
    import { useEffect, useMemo, useRef } from "react";
    import { usePathname } from "next/navigation";
    import { getCachedScrollState, saveScrollState } from "@/lib/scroll-cache";
    
    export function useRestoreVirtualScroll({ itemCount, estimateSize }) {
      const pathname = usePathname();
      const cacheKey = `scroll-restoration:${pathname}`;
    
      // 1. Retrieve the snapshot immediately during the first render
      const { initialOffset, measurementsCache } = useMemo(
        () => getCachedScrollState(cacheKey),
        [cacheKey]
      );
    
      const virtualizer = useWindowVirtualizer({
        count: itemCount,
        estimateSize: () => estimateSize,
        initialOffset,
        initialMeasurementsCache: measurementsCache,
        overscan: 10,
      });
    
      // 2. The Cleanup Hook: Fires when the user navigates away
      useEffect(() => {
        return () => {
          // We save the 'current' values from the virtualizer instance
          saveScrollState(
            virtualizer.scrollOffset,
            virtualizer.measurementsCache,
            cacheKey
          );
        };
      }, [virtualizer, cacheKey]);
    
      return virtualizer;
    }
`
