### ISSUE TITLE
`npm install @tanstack/react-virtual@latest` installs alpha.0, while beta.18 is actually latest

### ISSUE THREAD

**Issue by everdimension** [TanStack/virtual#380]
### Describe the bug

Pretty much the title, thanks!

### Your minimal, reproducible example

-

### Steps to reproduce

`npm install @tanstack/react-virtual@latest` installs 3.0.0-alpha.0, while 3.0.0-beta.18 is expected

### Expected behavior

3.0.0-beta.18

### Platform

macOS 11.5.1 

### tanstack-virtual version

v3.0.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is correct because all these releases are tagged with beta.

**Comment by MohamedLamineAllal** [comment]
To note the alpha is a breaking change. `useVirtual` instead of `useVirtualizer`. And it's not compatible with the existing doc as well.

**Comment by jvinhit** [comment]
I also got the same error, please public beta version to v3. ^^

**Comment by KevinVandy** [comment]
> I also got the same error, please public beta version to public v3.
> Many thank ^^

This library is still in beta so you have to add '@beta' to the package name. This is intentional.

**Comment by lgraubner** [comment]
This is quite confusing. I also ran into this and had to check why the api differs from the documentation. I would expect to get v2 with `@latest`. `v3@beta` would be fine as well, but alpha doesn't make any sense.

**Comment by alok-runner** [comment]
this only makes sense if the existing `latest` tag was an actual stable version, but since it is currently pointed at an alpha, the beta is actually "more latest" than the current "latest"

**Comment by maksym-boytsov** [comment]
Agree with @alok-runner.
I'm pretty that such a small DX issue is taking some part of the devs out using the package

**Comment by wub** [comment]
@tannerlinsley This tripped me up as well. Might want to double check this. It means that following the official docs results in an error right off the bat!

**Comment by tannerlinsley** [comment]
We're releasing soon on main. Stay tuned.
