### ISSUE TITLE
Re-rendering the Virtual list parent component

### ISSUE THREAD

**Issue by ajcodeskills** [TanStack/virtual#395]
### Describe the bug

There is a useReducer hook used in useVirtualizerBase hook and that causing the re-rendering of VirtualList component, have checked via **whyDidYouRender** library. I want to know, is it an expected behaviour or it can be resolved?

Attached the reproducible example, can observe the console. After each row while scrolling it will re-render the component.

### Your minimal, reproducible example

https://codesandbox.io/s/react-virtualized-infinite-scroll-demo-forked-zn1weo?file=/src/reactVirtual.js

### Steps to reproduce

1. Open the codesandbox link.
2. Scroll up
3. Observe the console while scrolling.

### Expected behavior

While scrolling, the components won't be rendered again and again.

### How often does this bug happen?

Every time

### Platform

Chrome

### tanstack-virtual version

v3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@ajcodeskills yes it expected behaviour, basic this is how hooks works and it's fine, re-renders are fine. You can limit re-rendering of items by wrapping it with memo.

**Comment by ajcodeskills** [comment]
Thanks @piecyk for response.
