### ISSUE TITLE
Blank screen on fast scroll

### ISSUE THREAD

**Issue by ajcodeskills** [TanStack/virtual#408]
### Describe the bug

While fast scrolling there is some delay in painting the content on viewport that's why for some time, the blank screen will appear. 
1. Can it be possible to handle the scroll velocity?
2. When can we expect a stable version, currently we have to manually specify the version?

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/virtual/tree/beta/examples/react/fixed?from-embed

### Steps to reproduce

1. Open the link.
3. Reduce CPU throttling by 6x down. (Lower end device)
4. Refresh and scroll fast, you will se the blank screen for sometime.

### Expected behavior

No Blank screen should be visible.

### Platform

Chrome

### tanstack-virtual version

v3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ajcodeskills** [comment]
@piecyk can you please address this issue?

**Comment by piecyk** [comment]
@ajcodeskills you could delay scroll with observeElementOffset that provides offset, but would not expect that it will make things better on lower end devices. 

Latest beta expose isScrolling flag, maybe use it to show some placeholder when scrolling.

**Comment by Sphinm** [comment]
> @ajcodeskills you could delay scroll with observeElementOffset that provides offset, but would not expect that it will make things better on lower end devices.
> 
> Latest beta expose isScrolling flag, maybe use it to show some placeholder when scrolling.

Can you give me a demo on how to use observeElementOffset? I'm using observeElementOffset and can't print out the log.

```
import { useVirtualizer, observeElementOffset } from '@tanstack/react-virtual';

const parentRef = useRef<any>();

const virtualizer = useVirtualizer({
    count: 200,
    getScrollElement: () => parentRef.current,
    estimateSize: () => 80,
    overscan: 10,
    debug: true,
    scrollingDelay: 1000,
});

useEffect(() => {
    if (parentRef.current) {
        observeElementOffset(parentRef.current, (offset: any) => {
            console.log('---Element offset:', offset);
        });
    }
});

```

**Comment by piecyk** [comment]
@Sphinm you need to pass it as option, scrollingDelay is just for isScrolling timeout, not the best name.

```tsx
const virtualizer = useVirtualizer({
  count: 200,
  getScrollElement: () => parentRef.current,
  estimateSize: () => 80,
  overscan: 10,
  debug: true,
  // scrollingDelay: 1000,
  observeElementOffset: (instance, cb) => {
    return observeElementOffset(instance, (offset) => {
      console.log('offset', offset)
      cb(offset)
    })
  },
})
```

**Comment by Sphinm** [comment]
@piecyk Thanks for the answer. Is there any good way to delay scrolling? For example, add throttle to the onScroll event.
Can it be like this?
```
import throttle from 'lodash.throttle'
observeElementOffset: (instance, cb) => {
    return observeElementOffset(instance, (offset) => {
      console.log('offset', offset)
      throttle(cb(offset),100)
    })
  },
```
