### ISSUE TITLE
Increasing cursor offset to scroll handle when scrolling

### ISSUE THREAD

**Issue by Mario-Eis** [TanStack/virtual#421]
### Describe the bug

Just go to the docs and use the vertical (!) scroll bar of a dynamic list. Click and hold the scroll handle and scroll repeatedly up and down a bit. The cursor will get a greater offset upwards with every up-down movement.

https://tanstack.com/virtual/v3/docs/examples/react/dynamic

UPDATE: It seems this started with version beta 21.

### Expected behavior

The cursor should stay at the scroll handle.

### How often does this bug happen?

Every time

### Platform

Windows

### tanstack-virtual version

3.0 beta 22

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Mario-Eis** [comment]
![test](https://user-images.githubusercontent.com/17924929/205033664-ba287338-b5d2-4bb7-b808-054fddc8d882.gif)

**Comment by ZakisM** [comment]
Hi, i'm also facing this issue, is there any workaround?

**Comment by Mario-Eis** [comment]
> Hi, i'm also facing this issue, is there any workaround?

Not any I am aware of. Our workaround is to use version 3.0.0-beta.18. This is the latest, not affected version.

**Comment by piecyk** [comment]
Hi, looks like it's connected with chrome, basic when reading size of element and it's different from estimated size we need to recalculate the whole measurements array that kinda slows the scroll.

**Comment by piecyk** [comment]
> Would a custom scrollbar implementation fix this, so it's consistent across all browsers?

@ZakisM no, as it's not connected to scrollbars, it's boils down how browsers is handling stuff when scrolling. We could try to defer the measurements but then when dragging most cases the items will have wrong positon.

**Comment by Mario-Eis** [comment]
Is this a "wont fix"? This "offset" behaviour seems still present.
