### ISSUE TITLE
Calling rowVirtualizer.measure() makes measurements of visible elements stale

### ISSUE THREAD

**Issue by akraines** [TanStack/virtual#425]
### Describe the bug

Render a table with dynamic rows
call rowVirtualizer.Measure
the the size field of the virtual rows will equal the estimated height
And the totalSize is off

### Your minimal, reproducible example

https://codesandbox.io/s/tender-thompson-qk1sy7?file=/src/main.tsx

### Steps to reproduce

See the console in the above sandbox.

### Expected behavior

The size of the virtual rows should be remeasured.

### Platform

windows

### tanstack-virtual version

v3 beta 22

### Additional context

In my case, the height of the list remained out of sync until I forced it to rerender eg. by sorting a column.
My workaround was to manaully mease the visible rows immediately after calling measure:
        //Clear the cache
        rowVirtualizer.measure();
        //Measure visible rows
        const {measureElementCache} = rowVirtualizer;
        _.map(rowVirtualizer.getVirtualItems(), r => {
            const curElement = measureElementCache[r.index];
            if (curElement) rowVirtualizer.measureElement(curElement);
        });

My suggested fix is to include that logic as part of the reset function "measure"

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Updated your example to show how totalSize size will change https://codesandbox.io/s/lucid-franklin-dvvly7?file=/src/main.tsx Imho looks ok, resize observer kiks in and update sizes 🤔

**Comment by akraines** [comment]
In my real life use case the resize observer wasn’t kicking in since my row
sizes depended on their content which didn’t change but the list height
depended on the total size which went out of sync. So my example doesn’t
demonstrate this since I was changing the row height when I was resetting
the rows.

**Comment by piecyk** [comment]
> In my real life use case the resize observer wasn’t kicking in since my row
sizes depended on their content which didn’t change but the list height
depended on the total size which went out of sync. 

hmm that is strange, as the total size is calculated based row size 🤔

**Comment by akraines** [comment]
Exactly – when you reset the measure case, the size is based on the estimated size until the next measure and in my case the measure doesn’t happen until there is a resize and since my sizes are staying the same there is no resize so the sizes are wrong and therefore the total size is wrong. That is how I understand the issue and that is how my proposed solution works: it manually calls measure on the visible rows so that the reset cache is correct for those rows.

**Comment by piecyk** [comment]
Ooo now i think got it, basic you only want to have in total size real sizes of visible items, and rest should be reverted to estimateSize.

**Comment by akraines** [comment]
Here is an updated sample: https://codesandbox.io/s/autumn-pine-1mis64

**Comment by piecyk** [comment]
> My suggested fix is to include that logic as part of the reset function "measure", so calling measure would include the above logic and I would fall into the pit of success.

i think this fix will not work for example scrolling in the middle of the list. Then after calling `measure ` we would also need to sync scroll position, otherwise visible items will change.

**Comment by piecyk** [comment]
> Resize observer shuld solve that – since non existent rows will be measured when they are first rendered

No as basic, by calling measure we are removing all the sizes that we read before scrolled to the middle, and based on that sizes the start of each item is calculated so the position. 

Overall calling measure is most cases a bad idea, maybe you could create real time example why you need to call it?

**Comment by sayo96** [comment]
@piecyk I'm running into a similar scenario. I render a list of items through react virtual. In my app i have the option to move the rendered items up or down from their current position. After i move an item upwards or downwards from it's current position i'm unable to trigger a remeasure.  Please let me know how should i solve this...

**Comment by manuelgeek** [comment]
For me it was because I enabled horizontal scrolling on the parent div.
