### ISSUE TITLE
Uncontrolled scrolling

### ISSUE THREAD

**Issue by chenjiandmw** [TanStack/virtual#426]
### Describe the bug

When used with react table, scroll uncontrollably to the bottom

### Your minimal, reproducible example

https://codesandbox.io/s/jovial-tesla-u2ngs8?file=/src/App.js

### Steps to reproduce

1. Scrolling the x-axis makes the first column invisible
2. Drag the y-axis scroll bar down

### Expected behavior

Follow the mouse

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/54097812/202077053-c2fdcaea-187a-4afe-a363-9f7f3e392b4c.mp4

### Platform

Windows

### tanstack-virtual version

v3.0.0-beta.23

### Terms & Code of Conduct

- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
- [X] I agree to follow this project's Code of Conduct

**Comment by dianventer** [comment]
I'm facing the same issue.

**Comment by dianventer** [comment]
Bump

**Comment by piecyk** [comment]
Hi, checking it out, looks like it's know issue on chrome. Here is similar problem on react-virtuoso side, great comment from @petyosi https://github.com/petyosi/react-virtuoso/issues/609#issuecomment-1135406208 to add colspan kida fix this scroll to bottom, but still there is another issue that something is trigger scroll making the list auto scroll. 

```tsx
{paddingTop > 0 && (
  <tr>
    <td colSpan={8} style={{ height: `${paddingTop}px` }} />
  </tr>
)}
```

**Comment by petyosi** [comment]
@piecyk I am certain that you're having the same issue as the one you've linked to.

**Comment by andreasrossa** [comment]
I had the same problem, only in Chrome. It worked in firefox.

If you have the same situation, try to add

`style={{ overflowAnchor: "none" }}` to your overflowing div.

[Where I found the fix](https://stackoverflow.com/questions/42958463/stop-automatic-scrolling-on-page-content-change)
