### ISSUE TITLE
Example with react-table v8?

### ISSUE THREAD

**Issue by MarksCode** [TanStack/virtual#433]
### Describe the bug

I see there's a demo for react-table v8 with react-window v2, but I don't see one using v3 anywhere. Does anyone know if the 2 libraries work together?

### Your minimal, reproducible example

https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/virtualized-rows?from-embed=&file=/src/main.tsx:3975-4024

### Steps to reproduce

N/A

### Expected behavior

N/A

### Platform

Mac/Windows

### tanstack-virtual version

v3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by suparerkk** [comment]
Yes, I can confirm it is working with react-table v8
https://codesandbox.io/s/example-with-react-table-v8-v95utd

I'm just forked from https://codesandbox.io/s/github/tanstack/table/tree/main/examples/react/virtualized-rows?from-embed=&file=/src/main.tsx:3975-4024 and made changes a few lines

**Comment by Zertz** [comment]
FWIW, the example above crashes when I scroll to the bottom of the table:

![image](https://user-images.githubusercontent.com/2636763/213210343-2b06394b-63d0-46fd-af3f-6f92377a2989.png)

**Comment by canastro** [comment]
@Zertz were you able to figure out whats wrong with this sandbox?
