### ISSUE TITLE
Messy row alignment due to wrong measurement of virtualizer items

### ISSUE THREAD

**Issue by sayo96** [TanStack/virtual#437]
### Describe the bug

I have used the same code mentioned in https://react-virtual-v2.tanstack.com/examples/dynamic.  Apart from the code here i have added logic to move a row item up or down.  When i moved a row item up a blank line appeared in the middle. I'm not sure what i'm missing. Please help 🙏 

### Your minimal, reproducible example

https://react-virtual-v2.tanstack.com/examples/dynamic

### Steps to reproduce

1. Add logic to move row item upwards from it's original position (ie change the data array you pass in)
2. When you move the row item you will see the blank line

### Expected behavior

I wasn't expecting the blank line to appear since we have necessary styles to position items one below the other 

### How often does this bug happen?
 I'm running into this frequently

### Screenshots or Videos

<img width="845" alt="Screenshot 2022-12-01 at 10 33 50 am" src="https://user-images.githubusercontent.com/26695583/204969884-7cc0074e-31f0-41f5-9193-0a2140f2c134.png">

### Platform

macOS, Chrome

### tanstack-virtual version

2.10.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sayo96** [comment]
I have found out what is happening:
1. Initially all the rows are measured properly. When i add a new row below the first row  the size of the rows are as follows 
row 1  size : 242
row 2 size (newly added row ) : 26
row 3 size: 242 
2. When i move the newly added row upwards, i was expecting the sizes to be :
row 1  size (newly added row ): 26
row 2 size (newly added row ) : 242
row 3 size: 242

**Comment by piecyk** [comment]
Hi @sayo96 looks like you are using v2 that doesn't support observing element for size change, please update to latest beta. Thanks.

**Comment by sayo96** [comment]
> Hi @sayo96 looks like you are using v2 that doesn't support observing element for size change, please update to latest beta. Thanks.

Hey @piecyk. Can the latest beta be used on production?

**Comment by piecyk** [comment]
Yes.
