### ISSUE TITLE
can't render all items in next js

### ISSUE THREAD

**Issue by chengjunzhang61** [TanStack/virtual#444]
### Describe the bug

I just copy and pasted this [example](https://codesandbox.io/s/awesome-haibt-4mt0vk?file=/src/main.tsx) into my application.
But i could not load all items 

### Your minimal, reproducible example

https://stackblitz.com/edit/github-y28bez-ztaklu?file=src%2Fpages%2Findex.tsx,src%2Fpages%2Fabout.tsx

### Steps to reproduce

- create next js project
- You can just copy and paste the code https://codesandbox.io/s/awesome-haibt-4mt0vk?file=/src/main.tsx
- I want to load 1000 items but can see only 49 items.
- can not pass the HTMLDivElement to `getScrollElement` because it always require `Window | null` type

### Expected behavior

Need to see all items.

### How often does this bug happen?

None

### Screenshots or Videos

https://jmp.sh/WRNisyX2

Please look at this recording

### Platform

- MacOS m1 chip
- React 17
- Next js 12.2.5

### tanstack-virtual version

3.0.0-beta29

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by charkour** [comment]
Hey @chengjunzhang61, 

I've noticed similar bugs like this as well. Doing a full page refresh in the browser, rather than rely on hot-module-reloading from a file save did the trick for me. I believe it's a bug with HMR

Another way to try fixing this is to build and run the next.js app locally.

**Comment by vass-david** [comment]
Seeing same bug in storybook due to hotreload. It's a bit annoying when I'm trying to fine tune the ux. Any idea how to fix this? Some callback to call, reset cache or something?
