### ISSUE TITLE
Infinite virtual list re-renders when used with SolidStart

### ISSUE THREAD

**Issue by aidanaden** [TanStack/virtual#450]
### Describe the bug

I'm trying to create an infinite virtual list in my solidstart project but ran into an issue where scrolling to the bottom of the list causes the page to re-render, instead of fetching more items to add to the list.

- When tested **without** solidstart, everything works fine [example](https://stackblitz.com/edit/solidjs-templates-tdvm1x?file=src/App.tsx)
- When tested **with** solidstart, page re-renders after reaching the bottom of the list [example](https://stackblitz.com/edit/solidjs-templates-np9gbb?file=src/routes/index.tsx)

### Your minimal, reproducible example

https://stackblitz.com/edit/solidjs-templates-np9gbb?file=src/routes/index.tsx

### Steps to reproduce

1. Go to stackblitz example
2. Scroll down the infinite virtual list
3. Page re-renders after reaching end of list with the new items rendered

### Expected behavior

As a user, I expected the infinite virtual list to render the additional items when approaching the end of list, but I am seeing the page get re-rendered with the additional items rendered in the virtual list

### How often does this bug happen?

Every time

### Platform

Windows with Ubuntu WSL, Chrome and Brave

### tanstack-virtual version

3.0.0-beta.30

### TypeScript version

v4.8.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by LXGaming** [comment]
I've just encountered this issue, I looked at [solidjs/solid-start](https://github.com/solidjs/solid-start) issues and quickly found the answer https://github.com/solidjs/solid-start/issues/547#issuecomment-1370606438
