### ISSUE TITLE
`Maximum update depth exceeded` when filtering a virtual list. 

### ISSUE THREAD

**Issue by paslo22** [TanStack/virtual#452]
### Describe the bug

I'm using react-virtual as the Menu List in a input select component using [react-select lib](https://react-select.com/).

Everything works great until the user tries to filter (search) the option list and the list gets shorter than the height of the virtual container, in the codesandbox example, 400px.

The weirdest part is that, if you change the height of that container, it doesn't crash.

My use case happens when using react-select, so my reproducible example is using that.
I can try to reproduce the same thing without using react-select but it would take me some more time.

### Your minimal, reproducible example

https://codesandbox.io/s/blissful-agnesi-ybximc?file=/src/MenuList.tsx

### Steps to reproduce

1. Click the first select component.
2. Type a name to search, example: `Melissa`.
    Make sure to type enough chars so the list of options gets shorter than the actual virtual div.
3. It crashes.

### Expected behavior

Should show the list of filtered results.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1653135/208991279-6cfc072d-3800-48fc-8632-0668132d2c6d.png)

### Platform

- OS: Linux.
- Browser: Tested in Chrome and Firefox.

### tanstack-virtual version

3.0.0-beta.30

### TypeScript version

4.4.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Hi will check why we got this. From quick look, i think the count should be taken from children, not options ( as they don't change when typing ) https://codesandbox.io/s/async-snowflake-tuk41i?file=/src/MenuList.tsx

**Comment by paslo22** [comment]
Hey! Nice. That did solve my problem.
You can close the issue if you think there is nothing else to investigate about it.

Just out of curiosity, do you think it's because `react-select` is doing way too many re renders? Or is it something else?
Because it doesn't explain the reason why it did work with a bigger virtual container 🤔

**Comment by piecyk** [comment]
> Just out of curiosity, do you think it's because react-select is doing way too many re renders? Or is it something else?
Because it doesn't explain the reason why it did work with a bigger virtual container 🤔

@paslo22 no, it was not because of react-select. With bigger virtual container we can fit more items, so the amount of re-renders is smaller.
