### ISSUE TITLE
scrollToIndex doesn't work correctly with dynamic height

### ISSUE THREAD

**Issue by irynakashchuk** [TanStack/virtual#468]
### Describe the bug

Hi,

I tried `setTimeout` and `requestAnimationFrame` as was discussed in [prev issue](https://github.com/TanStack/virtual/issues/216) but it doesn't work.

Simple retro: [https://codesandbox.io/s/busy-vaughan-5kzyme](https://codesandbox.io/s/busy-vaughan-5kzyme)

### Your minimal, reproducible example

https://codesandbox.io/s/busy-vaughan-5kzyme

### Steps to reproduce

1. Click on button "Scroll to row 250" (simple repro project)

### Expected behavior

Actually, it scrolls on 117

### How often does this bug happen?

Every time

### Platform

OS: MacOS,
Browser: Chrome v.107.0.5304.110

### tanstack-virtual version

3.0.0-beta.23

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by irynakashchuk** [comment]
I just checked the last version ("3.0.0-beta.35") and it works there, I'm not sure whether you need this fix you mentioned before...

**Comment by piecyk** [comment]
@irynakashchuk overall scroll to index in dynamic case is pretty tricky when scrolling to index we didn't see before. In 3.0.0-beta.35 there was different approach that was not working in some corner cases. Please checkout the latest version.
