### ISSUE TITLE
Sveltekit overscan issue with loading images

### ISSUE THREAD

**Issue by JohnRSim** [TanStack/virtual#471]
### Describe the bug

Overscan is working very differently between React with Svelte.

As a basic test I added a fake image to see how the images were loading triggering 404. 
```
<img src="{virtualRow.index}.png" />
```

With React as you scroll it is loading 1 row at a time and pulling an image at the end of the range.
With Svelte it is  loading in 1 Row the same as react but then it rerenders all the rows and tries to re-render all the images that are loaded - this is causing a flicker effect on the screen when images are added within the rows and why when there is just text it is now flickering.

I can create a quick video to demo this.

### Your minimal, reproducible example

https://stackblitz.com/edit/vitejs-vite-hds9nm?file=src%2FApp.svelte,package.json

### Steps to reproduce

Load example 
- open chrome tools and view network..
- scroll down to row 20 
- clear network tab 
- slowly scroll down or up by 1 row to trigger overscan to load next or previous row on overscan amount ie 5 in demo.
- Notice the re-render and all the other images on all the rows try to reload? 

ie here you can see initial row 32 loads as expected as I scroll down by 1 row and trigger overscan to load next row but then all of the other rows suddenly try to rerender and try to load all those images.. This does not happen with react.
![image](https://user-images.githubusercontent.com/364208/212349928-88476dc1-2252-49bc-8ce3-1f4bef649bee.png)

### Expected behavior

Same functionality as React where the rows are not all being rerendered as you scroll past the initial over scan amount and only 1 row loads at a time. 

### How often does this bug happen?

Every time

### Platform

Windows Chrome

### tanstack-virtual version

3.0.0-beta.35

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by JohnRSim** [comment]
I've updated the loop logic temporarily as this using the $virtualizer.measurementsCache as a quick very rough test and appears to work well. 

I'll create a quick example and share to show the difference

```
<div style="height: 900px; width: 400px; overflow: auto; border: 1px solid red" bind:this={scrollElement}>
	{#if virtualizer}
		<div style="height: {$virtualizer.getTotalSize()}px; width: 100%; position: relative">
			{#each $virtualizer.measurementsCache as virtualRow, i}
				{#if ((i < $virtualizer.range.endIndex+5) && (i > $virtualizer.range.startIndex-5))}
					<div
						class="row"
						style="overflow:hidden; height: {virtualRow.size}px; transform: translateY({virtualRow.start}px)"
					>
						{virtualRow.index}
						<img src="{virtualRow.index}.png" />
					</div>
				{/if}
			{/each}
		</div>
	{/if}
</div>
````

**Comment by piecyk** [comment]
@JohnRSim i think you where missing the unique identifier (or "key") for the each block, checkout the docs https://svelte.dev/tutorial/keyed-each-blocks

When added `as virtualRow (virtualRow.key)}` to your example then it works, https://stackblitz.com/edit/vitejs-vite-ykh2nf

**Comment by JohnRSim** [comment]
Sorry - you are right.

Thanks @piecyk
