### ISSUE TITLE
Scrollbar bounces when reaching the bottom of visible items

### ISSUE THREAD

**Issue by agustaf9** [TanStack/virtual#480]
### Describe the bug

Scrolling to bottom of a visible table causes the scrollbar to bounce/jitter up and down and I am unable to scroll after.

### Your minimal, reproducible example

https://codesandbox.io/s/bold-rain-dxq0l6?file=/src/Table.js

### Steps to reproduce

See example

### Expected behavior

Scroll smoothly

### How often does this bug happen?

Every time

### Platform

Windows, Tested on latest chrome, edge and firefox

### tanstack-virtual version

3.0.0-beta.39

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@agustaf9 we need to work on our docs, with table we can't position rows absolute, but bit different approach, https://codesandbox.io/s/sad-tharp-brcd6b?file=/src/Table.js also updated your example to use useWindowVirtualizer
