### ISSUE TITLE
Virtual list is re-rendered with a stale range initially when changing options

### ISSUE THREAD

**Issue by zhouzi** [TanStack/virtual#485]
### Describe the bug

When changing `options.count` the list is re-rendered once with a stale range and is then re-rendered again with an updated range. It can lead to a flash of content.

### Your minimal, reproducible example

Preview: https://81gdxs.sse.codesandbox.io/
Edit: https://codesandbox.io/s/brave-firefly-81gdxs

### Steps to reproduce

1. Go to https://81gdxs.sse.codesandbox.io/
2. Open the browser debugger
3. Click on the button "20" in the page
4. The debugger will pause the execution, at this point you can observe that the list has been re-rendered with the new rows. But it doesn't render enough items to fill the visible area.
5. Resume execution, the list will be re-rendered with enough items to fill the visible area.

### Expected behavior

What is strange is that it does render with the new elements but some numbers are out of date. So the list is partially updated.

I would expect the list to re-render with everything updated in a single render. Or at least not render with partially updated data.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/2291025/214835443-5d387247-db02-45bf-9e40-1e66de4c31d0.mov

### Platform

- OS: MacOS
- Browser: Brave

### tanstack-virtual version

3.0.0-beta.39

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Hi, good catch 👍 What is happening here, is that we calculate new rage after count render, but when resolving indexes to render we alredy use new count. That's why there is this shift.  

> It can lead to a flash of content.

hmm didn't see that before 🤔 One workaround for now would be to call calculateRange in same time when count chanted, this can be done with useMemo, or having prevCount, etc.

```
  React.useMemo(() => {
    rowVirtualizer.calculateRange();
  }, [count, rowVirtualizer]);
 ```
 
 https://codesandbox.io/s/admiring-wright-fgfkpc?file=/src/main.tsx:417-508

**Comment by zhouzi** [comment]
> What is happening here, is that we calculate new rage after count render, but when resolving indexes to render we alredy use new count. That's why there is this shift.

Would it make sense to push a fix so range is re-calculated when resolving indexes? I'm happy to look into it. 

> > It can lead to a flash of content.
> 
> hmm didn't see that before 🤔

To be fair in most scenarios it happens too fast to be noticed. I'm working on a UI where's the lot going on, which is how I noticed it (that plus an issue with `scrollToIndex` but not sure if it's related yet).

> One workaround for now would be to call calculateRange in same time when count chanted, this can be done with useMemo, or having prevCount, etc.
> 
> ```
>   React.useMemo(() => {
>     rowVirtualizer.calculateRange();
>   }, [count, rowVirtualizer]);
> ```
> 
> https://codesandbox.io/s/admiring-wright-fgfkpc?file=/src/main.tsx:417-508

Thanks I'll give that a try in the mean time 👍

**Comment by piecyk** [comment]
> To be fair in most scenarios it happens too fast to be noticed. I'm working on a UI where's the lot going on, which is how I noticed it (that plus an issue with scrollToIndex but not sure if it's related yet).

fyi, scrollToIndex is bit tricky in dynamic case, as we do a jump and re-check if we are in correct place. Also one note that we can update scroll in render to have correct range in one render, have a look at reverse example https://github.com/TanStack/virtual/discussions/195#discussioncomment-4706845

**Comment by zhouzi** [comment]
I gave a try to the workaround you shared @piecyk and although it does work for re-renders, the issue still happens on the initial render:

https://user-images.githubusercontent.com/2291025/215020172-22771166-4a75-4a75-877a-9aa8646f6172.mov

https://codesandbox.io/s/great-bell-cpw6v1

The issue is that the `useEffect`'s callback is called after the first render. So the list was already rendered once with an invalid range. It seems to me that the range should be updated when the library calls a function that depends on it (such as `getIndexes`).

I'll suggest a fix.

**Comment by piecyk** [comment]
> The issue is that the useEffect's callback is called after the first render. So the list was already rendered once with an invalid range. It seems to me that the range should be updated when the library calls a function that depends on it (such as getIndexes).

no, the issue here is that in initial render we don't know the size of the container, as ref is set after first render. If you set the `initialRect` it will render correct range in first render https://codesandbox.io/p/sandbox/spring-tree-9d4gkq

**Comment by piecyk** [comment]
@zhouzi i think we can go with something like this https://github.com/TanStack/virtual/pull/487 basic calculate range but not trigger update.
