### ISSUE TITLE
When virtualized list height increases, not enough rows are rendered (until user scrolls)

### ISSUE THREAD

**Issue by msmithNI** [TanStack/virtual#492]
### Describe the bug

When using TanStack Virtual (recent beta build), if the height of the virtualized list increases, not enough rows are rendered in the new larger height, until the user scrolls.

This is reproducible in `@tanstack/virtual-core@3.0.0-beta.41` or newer (it looks related to the changes in #487 ). It does not reproduce with `v3.0.0-beta.40`.

### Your minimal, reproducible example

https://codesandbox.io/s/tanstack-virtual-b41-height-issue-ygnw5c

### Steps to reproduce

1. Load example ( https://ygnw5c.sse.codesandbox.io/ )
2. Click the [450px] button to increase the list height
  Result: List height increases, but not enough list items were rendered to fill the new list height
3. Scroll the list
  Note that now additional list items get rendered

### Expected behavior

I expected a height change of the list element to be sufficient to re-render enough new items to fill the new height.  
The virtualizer onChange gets called, but at that point, calling getVirtualItems will not return enough items based on the new height.

### How often does this bug happen?

Every time

### Screenshots or Videos

![TanstackVirtualHeightChangeBug](https://user-images.githubusercontent.com/20709258/216728505-95ea8819-0d0d-4551-9ae8-c4d90ce32f42.gif)

### Platform

Chrome 109 (Windows)

### tanstack-virtual version

3.0.0-beta.41

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@msmithNI thanks for reporting, should be fixed in latest beta 👍
