### ISSUE TITLE
estimateSize causes "Maximum update depth exeeded."

### ISSUE THREAD

**Issue by righ** [TanStack/virtual#499]
### Describe the bug

When using useVirtual in `@tanstack/react-virtual`, specifying [estimateSize](https://tanstack.com/virtual/v3/docs/api/virtualizer#estimatesize) prop causes the "Maximum update depth exeeded.".
If this is removed, the error will not occur.

### Your minimal, reproducible example

https://codesandbox.io/s/tanstack-virtual-estimatesize-error-gr7ffh?file=/src/App.tsx

### Steps to reproduce

Uncomment out the line of 'estimateSize'.

### Expected behavior

No error should occur when estimateSize is specified.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="721" alt="screenshot" src="https://user-images.githubusercontent.com/8147077/217592521-163d14dd-9957-42fe-9137-3202fe780caf.png">

### Platform

macOS

### tanstack-virtual version

3.0.0-alpha.0

### TypeScript version

4.4.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@righ please use latest beta, [v3.0.0-beta.46](https://github.com/TanStack/virtual/releases/tag/v3.0.0-beta.46)

**Comment by righ** [comment]
Understood. Thank you.
