### ISSUE TITLE
if image not found or it has errors it always keeps refreshing on scroll

### ISSUE THREAD

**Issue by tomas862** [TanStack/virtual#506]
### Describe the bug

Hello,

Not sure if its more related with how the virtualization behaves with images but for me it looks like an issue.

Description:

If you try to load image with placeholder if the image is not found or it has error, when network tab is opened, I see that requests are being made always when you scroll down or up (when elements that you loaded before re-appears in the DOM).

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/wizardly-minsky-eox24o?file=%2Fsrc%2Fmain.tsx

### Steps to reproduce

1. Open code sandbox link
2. Open sample widow and open browser dev tools.
3. Go to "network" tab.
4. Scroll up and down, you will see that the image is being requested always.

### Expected behavior

As a user, I would expect that when I visit same images second time, it should not attempt to load same images over and over again.

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/17051250/218728125-1ff0c4a3-8ea5-468e-a1fd-e4465f9ccd4c.mov

### Platform

Browser chrome

### tanstack-virtual version

3.0.0-beta.47

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Hi, basic it's how virtualization works, when scrolling rows are rendered and image will load. Should not be an issue as browser should cache the image and return it from cache.

**Comment by tomas862** [comment]
> Hi, basic it's how virtualization works, when scrolling rows are rendered and image will load. Should not be an issue as browser should cache the image and return it from cache.

Thanks for the confirmation - looked scary, but thought as well that browsers should do the job to lift this . Will close the issue
