### ISSUE TITLE
dynamic size issue

### ISSUE THREAD

**Issue by jvinhit** [TanStack/virtual#524]
### Describe the bug

Hi guys, I have an issue using virtual scroll with andt textbox ( must set autoSize config ). 
The issue occurs when **scrolling up**.  

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/gracious-blackwell-803fpo

### Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/gracious-blackwell-803fpo
2. Scroll up

### Expected behavior

I expected smooth behavior, but I see flickering content when scroll-up.

### How often does this bug happen?

Every time

### Platform

macOS

### tanstack-virtual version

3.0.0-beta.30

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
To help triage a lot of outdated issues, we're closing this due to its age. If this issue is still relevant, please tag @ tannerlinsley in a new comment confirming the case.
