### ISSUE TITLE
useVirtual or useVirtualizer? Infinite loop? Maximum depth exceeded? Correct version to install?

### ISSUE THREAD

**Issue by 55Cancri** [TanStack/virtual#526]
### Describe the bug

If I run `pnpm add @tanstack/react-virtual`, it installs version `"3.0.0-alpha.0"`. Doing that, it seems useVirtualizer is no longer a function and the api for useVirtual has changed substantially. So I tried the following code:
```typescript
const logVirtualizer = useVirtual({
    parentRef: logRef,
    onScrollElement: logRef,
    estimateSize: () => 30,
    size: logs.length,
  });
```

But this gives the error maximum call depth exceeded within `useVirtual`'s internal's. If this is not the correct version or stable version of `@tanstack/react-virtual`, which version should I use? I tried `pnpm add @tanstack/react-virtual@beta` and `pnpm add @tanstack/react-virtual@3`, but they both result in the infinite loop error. I also tried `pnpm add @tanstack/react-virtual@next` but that doesn't seem to exist. Is this package ready for use? Is my code correct? The docs don't seem to use `useViritual`.

### Your minimal, reproducible example

n/a

### Steps to reproduce

run `pnpm add @tanstack/react-virtual@beta`

### Expected behavior

I expect no infinite loops

### How often does this bug happen?

None

### Platform

macOS

### tanstack-virtual version

3.0.0-alpha.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@55Cancri please install latest beta with specify version `pnpm add @tanstack/react-virtual@3.0.0-beta.54`

**Comment by 55Cancri** [comment]
> @55Cancri please install latest beta with specify version `pnpm add @tanstack/react-virtual@3.0.0-beta.54`

Nice, thanks. Everything is working now, just needed to restart typescript server. This library is awesome. Closing.
