### ISSUE TITLE
`ResizeObserver` loop limit exceeded

### ISSUE THREAD

**Issue by MrZillaGold** [TanStack/virtual#531]
### Describe the bug

We use the module on a fairly large site and embed a virtual scroll in one of the parts of the site using ReactDOM. When navigating between pages, we do not cause unmount between pages - because this process is difficult to follow on a large-level project that uses many technologies and react is not the main one. 
Because of this, users often encounter an error: `ResizeObserver` loop limit exceeded

Looking for more information, I came across a hack that avoids this error, you need to wrap the ResizeObserver callback in an animationRequestFrame:

https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/58701523#58701523
https://github.com/PolymerLabs/uni-virtualizer/issues/112
https://github.com/nolimits4web/swiper/pull/5441

### How often does this bug happen?

Often

### Platform

- OC: any
- Browser: any

### tanstack-virtual version

3.0.0-beta.54

### TypeScript version

4.9.5

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by devcatalin** [comment]
I experience the same problem, using the `3.0.0-beta.54` version in a large React project, and this error appears sometimes. But, it's inconsistent and I was not able to reproduce it outside the project..

**Comment by piecyk** [comment]
I would recommended just to ignore this error, fixing it will not change anything, saying from experience as living with this in production few years now.

**Comment by MrZillaGold** [comment]
In our project, we can completely ignore this error in Sentry only because of this module, but then we will lose information about other errors of this kind in other parts of the site. I am aware that this error does not affect anything, but it still exists but the module has 1M monthly downloads, and someone will also encounter this and it seems logical to fix it so that there are no unnecessary issues.

**Comment by piecyk** [comment]
> In our project, we can completely ignore this error in Sentry only because of this module, but then we will lose information about other errors of this kind in other parts of the site.

Hard to say how you are handling errors internally, but just ignore errors having message, not all errors
```ts
const knownErrors = [
  'ResizeObserver loop completed with undelivered notifications.',
  'ResizeObserver loop limit exceeded'
]
```

> it seems logical to fix it so that there are no unnecessary issues 🤷‍♂️

Yeah, totally agree to fix it, but from my understanding we can't really. Patching it with requestAnimationFrame will not solve the underling issue.

**Comment by MrZillaGold** [comment]
![Снимок экрана 2023-04-18 в 15 53 28](https://user-images.githubusercontent.com/42776347/232783650-e5a6f7a8-b0d1-4312-b42c-10aa9490d8af.png)

In Safari this error is fatal and the component that uses the hook crashes. No longer looks like a minor error that can be ignored 🥲

**Comment by piecyk** [comment]
> ![Снимок экрана 2023-04-18 в 15 53 28](https://user-images.githubusercontent.com/42776347/232783650-e5a6f7a8-b0d1-4312-b42c-10aa9490d8af.png)
> 
> In Safari this error is fatal and the component that uses the hook crashes. No longer looks like a minor error that can be ignored 🥲

hmm, how so? Just tested `Safari 16.2 (18614.3.7.1.5)` got bunch of errors but nothing was affected 🤷‍♂️ 

<img width="498" alt="Zrzut ekranu 2023-04-18 o 16 01 12" src="https://user-images.githubusercontent.com/82964/232801567-7568adc3-26d5-495f-ad13-efa3da575016.png">

**Comment by dcworldwide** [comment]
Is this error logged only in non-production builds?

**Comment by tannerlinsley** [comment]
This error can be safely ignored. I wish there was a better answer.

**Comment by 3instein** [comment]
it's causing the scroll to go way up
