### ISSUE TITLE
Bug - when scroll-behavior is set to smooth, and scrolling using a scrollbar, it jumps up and down.

### ISSUE THREAD

**Issue by aleks-devel** [TanStack/virtual#539]
### Describe the bug

I'm using bootstap in a project, and I noticed that tanstack-virtual works very badly with it, after several tests, I realized that scroll-behavior which is set to smooth by default in bootstap breaks scrolling.

### Your minimal, reproducible example

https://codesandbox.io/s/affectionate-browser-3619bz

### Steps to reproduce

1. Open codesandobx
2. Grab scrollbar thumb, and quickly scroll to middle of the table.
3. You can see that the scrollbar starts jumping up and down.

### Expected behavior

Normal scrolling

### How often does this bug happen?

Every time

### Platform

OS: Fedora 37
Browser Chrome 111.0

### tanstack-virtual version

3.0.0-beta.54

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by aleks-devel** [comment]
If I remove the data-index from the table rows everything works fine. And the same problem is noticed in virtuoso.

**Comment by piecyk** [comment]
@aleks-devel native smooth scroll behaviour don't quite work when rows are dynamic, checkout this comment https://github.com/TanStack/virtual/discussions/495#discussioncomment-4886406

> If I remove the data-index from the table rows everything works fine. 

That is correct as then, list elements are fixed, we know each size and position when scrolling, and it will not change.

**Comment by aleks-devel** [comment]
@piecyk Thank you! How about saying this in the documentation? It will be useful for people using bootstrap.
