### ISSUE TITLE
ScrollToIndex on dynamic list issues - smooth behavior inconsistent, especially bad scrolling in "up" direction

### ISSUE THREAD

**Issue by prsauer** [TanStack/virtual#541]
### Describe the bug

We've seen inconsistent and strange behavior using scrollToIndex with behavior: smooth

It's reproduced in
https://codesandbox.io/p/sandbox/distracted-haslett-rd34sh?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A7%7D%5D

I'm open to thoughts about how we might work around this with better use of setTimeout / requestAnimationFrame / useEffect patterns. In the code sandbox above we are doing the scrolling inside a useEffect and requestAnimationFrame wrapper.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/distracted-haslett-rd34sh?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A7%7D%5D

### Steps to reproduce

1st test:
Just observe behavior
-Scrolling does not always occur correctly, seems correct roughly 50% of the time

2nd test:
Immediately hit "Scroll to end"
-Scrolling up behavior is very strange, lands in midway up the list at a very much incorrect location

Repeat tests with scroll behavior set to default.

### Expected behavior

Expected behavior: A new row will be highlighted and scrolled to the top about once every 4 seconds.

### How often does this bug happen?

None

### Platform

Windows / Chrome 112.0.5615.86

### tanstack-virtual version

3.0.0-beta.54

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by nadavschwartz** [comment]
I was looking for a solution to scroll to top functionality as well, and encountered an issue similar to yours. it would misbehave in strange ways.

my use case was while using the virtual list, I fetch data using useInfiniteQuery, and allowing the user filter results. to avoid unnecessary spams of requests when filters are being passed to the useInfiniteQuery, I scroll to the top.
so I added a useEffect hook that looks like that:
```
  React.useEffect(() => {
    if (filters && parentRef.current) {
      parentRef.current.scrollTop = 0;
    }
  }, [filters]);
```

so it's essentially scrolling to the top of the current ref when there's a change in the filter object.
I am not sure whether it's a stable fix, but it seems to work just fine for now. You can apply the same logic in your use case if you'd like.
