### ISSUE TITLE
Virtualized Element / Row disappears when drag and dropping

### ISSUE THREAD

**Issue by L-U-C-K-Y** [TanStack/virtual#543]
### Describe the bug

Hi @tannerlinsley 

Many thanks for this great library, the integration has been very simple compared to other virtualization / windowing libraries.

We face one issue in production that a virtualized row element disappears when dragging it.
I have attached a video:

https://user-images.githubusercontent.com/14868134/233421993-f5867d08-9637-43f0-8367-dfbd51889d45.mp4

### Your minimal, reproducible example

Sorry, I don't have one

### Steps to reproduce

I cannot share the full age code, but we this part (80%), I can share:

```typescript
import { useWindowVirtualizer } from '@tanstack/react-virtual';

  const virtualizer = useWindowVirtualizer({
    count: structureMembers.length || 0,
    estimateSize: () => 45,
    scrollMargin: virtualizedParentOffsetRef.current,
  });
  const virtualizedEmployees = virtualizer.getVirtualItems();

  return (
    <DndContext
      sensors={dragAndDropSensors}
      onDragEnd={(event) => {
        if (event.active.data?.current) {
          onDragEndOfEmployee(event);
        } else {
          onDragShiftEnd(event);
        }
      }}
    >
      <div>
        <SortableContext
          strategy={verticalListSortingStrategy}
        >
          <div ref={virtualizedParentRef}>
            <div
              style={{ height: virtualizer.getTotalSize() }}
            >
              <div
                style={{ transform: `translateY(${virtualizedEmployees?.[0]?.start - virtualizer.options.scrollMargin}px)` }}
              >
                {virtualizedEmployees.map((virtualRow) => (
                  <div
                    ref={virtualizer.measureElement}
                    key={virtualRow.key}
                    data-index={virtualRow.index}
                  >
                    <SortableItem
                      key={createCompositeKey([teamData.id, structureMembers[virtualRow.index].id])}
                      id={createCompositeKey([teamData.id, structureMembers[virtualRow.index].id])}
                    >
                      <CellsRow
                        employeeData={structureMembers[virtualRow.index]}
                        isFirst={virtualRow.index === 0}
                        isLast={virtualRow.index === structureMembers.length - 1}
                      />
                    </SortableItem>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </SortableContext>
      </div>
    </DndContext>
  );
```

We use https://dndkit.com/ for dnd.

### Expected behavior

I would expect that the employee would not disappear if dragged to far up and down (I assume out of the height).

### How often does this bug happen?

Every time

### Screenshots or Videos

https://user-images.githubusercontent.com/14868134/233421993-f5867d08-9637-43f0-8367-dfbd51889d45.mp4

### Platform

I tested on MacOS 13 and the newest Chrome

### tanstack-virtual version

"@tanstack/react-virtual": "^3.0.0-beta.54",

### TypeScript version

    "typescript": "^4.3.4"

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
This is because the element goes out of the visible range when you scroll it up or down. The solution is to make sure you are returning the index of element you are dragging in the rangeExtractor so it's ensured to be rendered regardless of the scroll position.
