### ISSUE TITLE
unable to use w/ rem units

### ISSUE THREAD

**Issue by bstro** [TanStack/virtual#546]
### Describe the bug

I'm attempting to use `rem` units instead of `px` units to easily fit w/ my tailwind scales, and this seems to break my component as soon as I attempt to scroll within the scrollable frame.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/unruffled-hypatia-brmipn?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A16%7D%5D

### Steps to reproduce

1. Focus inside the scrollable div
2. Scroll

### Expected behavior

N/A

### How often does this bug happen?

None

### Screenshots or Videos

![repro](https://user-images.githubusercontent.com/627290/234408119-f8c25ee4-632c-4183-b8c1-5a781d19d601.gif)

### Platform

macOS, Chromium 112.0.5615.49

### tanstack-virtual version

3.0.0-beta.54

### TypeScript version

5.0.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by JonathanGafar** [comment]
Any luck on this? I'm having the same issue.

**Comment by KevinVandy** [comment]
I don't think it is meant to work with any unit besides pixels. Better finer grain math under the hood. TranslateY is often works best as a standalone style separate from the rest of your CSS.
