### ISSUE TITLE
Running virtual examples with React 18 createRoot causes rendering lag

### ISSUE THREAD

**Issue by bwamsellem** [TanStack/virtual#549]
### Describe the bug

I have tested the examples/react/fixed example with React 18, so changed the init code to use the new createRoot / render API:

ReactDOM.render(  <App /> , document.getElementById('root'))
=>
ReactDOM.createRoot( document.getElementById('root')).render(  <App /> )

Before: the scrolling is super smooth, 
After: you can notice an important lag ( white flickering) while scrolling through rows or grid.

Is this caused by the concurrent rendering of React 18? 

### Your minimal, reproducible example

https://react-ts-mfeisb.stackblitz.io

### Steps to reproduce

1. Run the example in dev mode

### Expected behavior

Smooth scrolling

### How often does this bug happen?

Every time

### Platform

Windows 10 + Chrome 113

### tanstack-virtual version

3.0.0-beta.54

### TypeScript version

4.4.2

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@bwamsellem kinda looks ok for me, can you create small clip showing the issue. 

> Is this caused by the concurrent rendering of React 18?

no, i don't think so.

**Comment by bwamsellem** [comment]
Thanks. Do you reproduce the issue ?

**Comment by bwamsellem** [comment]
Yes, I will do.

**Comment by bwamsellem** [comment]
Here are two video clips showing the normal behavior (old React API) , and the slow one ( new React 18 API).

https://github.com/TanStack/virtual/assets/114481349/0bb6e1fb-f09d-411f-b22c-f87d7d60d9a5


https://github.com/TanStack/virtual/assets/114481349/8d06248b-4265-4202-81e6-0e32ef4375cc

**Comment by igortas** [comment]
Having same lag issue, table looks like it's not virtualized at all.

**Comment by manelio** [comment]
I faced that problem months ago. My project makes intensive use of virtualization to create Excel-like spreadsheets and I switched from `react-virtualized` to `@tanstack/virtual`, and I had to make some adaptations to avoid unnecessary renders.

Anyway, for the problem you mention, my solution involves using a modified version of `@tanstack/react-virtual` (it's just a file without relative references):

Source code is [here](https://raw.githubusercontent.com/TanStack/virtual/beta/packages/react-virtual/src/index.tsx):

Instead of

```
import { useVirtualizer } from '@tanstack/react-virtual';
```

I use

```
import { useVirtualizer } from './react-virtual.custom';
```

And I only make a small change to invoke `rerender` from `react-dom`'s `flushSync`:

Original:

```
const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> = {
  ...options,
  onChange: (instance) => {
    rerender()
    options.onChange?.(instance)
  },
}
```

Modified:

```
import { flushSync } from 'react-dom'

const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> = {
  ...options,
  onChange: (instance) => {
    queueMicrotask(() => {
      flushSync(() => {
        rerender()
      })
    })
    options.onChange?.(instance)
  },
}
```

I believe that the entire onChange callback or the rerender call should be overridable by the user. I am not an expert in Typescript and I am not clear about the best approach, but I will create a pull request in case any maintainer finds the change interesting to add.

**Comment by nongdinhtuyen** [comment]
> I faced that problem months ago. My project makes intensive use of virtualization to create Excel-like spreadsheets and I switched from `react-virtualized` to `@tanstack/virtual`, and I had to make some adaptations to avoid unnecessary renders.
> 
> Anyway, for the problem you mention, my solution involves using a modified version of `@tanstack/react-virtual` (it's just a file without relative references):
> 
> Source code is [here](https://raw.githubusercontent.com/TanStack/virtual/beta/packages/react-virtual/src/index.tsx):
> 
> Instead of
> 
> ```
> import { useVirtualizer } from '@tanstack/react-virtual';
> ```
> 
> I use
> 
> ```
> import { useVirtualizer } from './react-virtual.custom';
> ```
> 
> And I only make a small change to invoke `rerender` from `react-dom`'s `flushSync`:
> 
> Original:
> 
> ```
> const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> = {
>   ...options,
>   onChange: (instance) => {
>     rerender()
>     options.onChange?.(instance)
>   },
> }
> ```
> 
> Modified:
> 
> ```
> import { flushSync } from 'react-dom'
> 
> const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> = {
>   ...options,
>   onChange: (instance) => {
>     queueMicrotask(() => {
>       flushSync(() => {
>         rerender()
>       })
>     })
>     options.onChange?.(instance)
>   },
> }
> ```
> 
> I believe that the entire onChange callback or the rerender call should be overridable by the user. I am not an expert in Typescript and I am not clear about the best approach, but I will create a pull request in case any maintainer finds the change interesting to add.

It doesn't work with useWindowVirtualizer, and I still experience white flickering when scrolling the screen

**Comment by tannerlinsley** [comment]
If this is still an issue for you, please comment here and tag me and I'll reopen the issue and work on it. Thanks!

**Comment by 1MaTo** [comment]
@tannerlinsley Will you fix it in the future updates? 
Current tanstack-virtual examples use React 17, and this issue still present for React 18 as shown on 2 clips by [bwamsellem](https://github.com/bwamsellem)
So the current solution for React 18 is use deprecated render method or make custom changes in package as suggested above

**Comment by piecyk** [comment]
> @tannerlinsley Will you fix it in the future updates? Current tanstack-virtual examples use React 17, and this issue still present for React 18 as shown on 2 clips by [bwamsellem](https://github.com/bwamsellem) So the current solution for React 18 is use deprecated render method or make custom changes in package as suggested above

This is interesting issue, like dynamic examples is using react 18 and works correct https://tanstack.com/virtual/v3/docs/examples/react/dynamic

let see, planing to update other examples and simplify them a bit.

**Comment by piecyk** [comment]
@1MaTo as mention before this is tricky issue, there are many reasons why it's happening 
* like browse internal implementation ( noticed that currently Firefox doing best job here ) 
* interesting caveats with chrome, for dynamic case when we use resize observer to watch items sizes the scroll handle lag behind #421
* hardware performance, when running low on battery seeing more white space as browser can't keep up with rendering  
 
Going back to react 18, as @manelio noticed we can use flushSync, but let's use it only when scrolling, checkout #608

Overall it's pretty hard to test, any help would be greatly appreciated.

**Comment by airstrike** [comment]
> Source code is [here](https://raw.githubusercontent.com/TanStack/virtual/beta/packages/react-virtual/src/index.tsx):

Thanks for sharing but this link has expired. Any chance you could point future readers to the example? Thank you very much!
