### ISSUE TITLE
Table column does not grow to account for content width

### ISSUE THREAD

**Issue by ntkzwane** [TanStack/virtual#553]
### Describe the bug

Table columns don't resize when the content is larger than the default width. This is reproducible by stopping the cell's content from wrapping - i.e set `white-space` to `nowrap`

### Your minimal, reproducible example

https://codesandbox.io/s/peaceful-sanne-ke9eu8?file=/src/App.js

### Steps to reproduce

- Go to the [react/dynamic](https://github.com/TanStack/virtual/tree/beta/examples/react/dynamic) example
- Update the `GridVirtualizerDynamic` render responsible for displaying the columns in the following way
  - Add the `white-space: nowrap` css rule
  - Remove the `width` and `minHeight` css rules - based on these suggestions:
    - https://github.com/TanStack/virtual/issues/23#issuecomment-1372524272
    - https://github.com/TanStack/virtual/issues/235#issuecomment-1002275125
    - https://github.com/TanStack/virtual/issues/376#issuecomment-1222346322
  - Add the appropriate `data-index` and `ref` so the cells get measured
- This is the resulting cell renderer
```jsx
{columnItems.map((column) => {
  return (
    <div
      key={column.key}
      data-index={column.index}
      ref={columnVirtualizer.measureElement}
      style={{
        borderBottom: '1px solid #c8c8c8',
        borderRight: '1px solid #c8c8c8',
        padding: '7px 12px',
        whiteSpace: 'nowrap',
      }}
    >
      {row.index === 0 ? (
        <div>{columns[column.index].name}</div>
      ) : (
        <div>{data[row.index][column.index]}</div>
      )}
    </div>
  )
})}
```

### Expected behavior

Expect the table's cells to grow to fit the content, without the columns falling out of sync. I would have assumed this to be the default behavior without adding the resize observer workaround (as suggested in this discussion https://github.com/TanStack/virtual/issues/28#issuecomment-976457408) since none of the contents in this table resize asynchronously since the content here is static

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1259" alt="Screenshot 2023-05-22 at 20 42 37" src="https://github.com/TanStack/virtual/assets/9074285/64182dea-f08b-4ac5-ae58-2cc500bb5d75">

### Platform

macOs: reproducible in Firefox and Chrome

### tanstack-virtual version

v3.0.0-beta.54

### Additional context

I've tried manually triggering remeasures _after_ the initial paint like in this workaround https://github.com/TanStack/virtual/issues/376#issuecomment-1222346322 with no success

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
I believe this has less to do with the virtualizer and more to do with how table layouts work in general. Happy to take a look if this is still an issue for you. If so, please comment and I'll reopen.

**Comment by ntkzwane** [comment]
Heya, thanks for the followup. I don't quite think it's a general table layout issue per say, it's mainly due to the fact that the rows are absolutely positioned, meaning the table body wouldn't automatically grow to fit the content

I would have hoped that the cell measurement would rectify this, though it doesn't seem to be the case - explicitely remeasuring after the initial paint still uses the incorrect widths sadly

**Comment by piecyk** [comment]
> Heya, thanks for the followup. I don't quite think it's a general table layout issue per say, it's mainly due to the fact that the rows are absolutely positioned, meaning the table body wouldn't automatically grow to fit the content
> 
> I would have hoped that the cell measurement would rectify this, though it doesn't seem to be the case - explicitely remeasuring after the initial paint still uses the incorrect widths sadly

@ntkzwane the issue here is that you measure columns in a loop so basic only last one wins, to make it correct you would need to store size column for each row and picked the largest

**Comment by ntkzwane** [comment]
> > Heya, thanks for the followup. I don't quite think it's a general table layout issue per say, it's mainly due to the fact that the rows are absolutely positioned, meaning the table body wouldn't automatically grow to fit the content
> > I would have hoped that the cell measurement would rectify this, though it doesn't seem to be the case - explicitely remeasuring after the initial paint still uses the incorrect widths sadly
> 
> @ntkzwane the issue here is that you measure columns in a loop so basic only last one wins, to make it correct you would need to store size column for each row and picked the largest

Yep yep, that's precisesly how I'm working around it right now. I think I made a bad assumption, I was under the impression that adding `ref={rowVirtualizer.measureElement}` and the appropriate `data-index` would ensure that the cell's width is measured correcty, and the column's width updated accordingly. I figured that this out-the box experience would be the most intuitive for consumers of the library.

**Comment by vusk8** [comment]
> I believe this has less to do with the virtualizer and more to do with how table layouts work in general. Happy to take a look if this is still an issue for you. If so, please comment and I'll reopen.

Hey @tannerlinsley, can you take a look on it, thank you.

**Comment by vusk8** [comment]
> I believe this has less to do with the virtualizer and more to do with how table layouts work in general. Happy to take a look if this is still an issue for you. If so, please comment and I'll reopen.

Hey @tannerlinsley, I am facing the same issue that I can't set 'nowrap' for the th and td, can you take a look on it
