### ISSUE TITLE
`Maximum update depth exceeded.` when defining `estimateSize` V2

### ISSUE THREAD

**Issue by maxime4000** [TanStack/virtual#555]
### Describe the bug

I'm building a table with V8 and Virtual V2.10.4. I try using V3, but so many bugs and incorrect trigger were happening.
Anyway, when I'm defining `estimateSize: () => 40`, I'm receiving this error. I'm using Styled-components and this happen

`
Unhandled Runtime Error
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
`

### Your minimal, reproducible example

https://codesandbox.io/s/angry-johnson-31uc03?file=/src/main.tsx

### Steps to reproduce

Mostly a Styled-components version of the same example found in the infinite Scrolling React-Table v8
The Sandbox doesn't show the same error, We are using NextJS

### Expected behavior

When setting the estimateSize, this shouldn't happen. The default estimateSize is () => 50 and it work, but if I define estimateSize: () => 50, it will break...

### How often does this bug happen?

Every time

### Platform

macOS
Chrome 

### tanstack-virtual version

2.10.4

### TypeScript version

5.0.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by johnvankeulen** [comment]
Wrapping `estimateSize` in a `useCallback` will probably fix your issue:
```diff
-    estimateSize: () => 40
+    estimateSize: React.useCallback(() => 40, [])
```
