### ISSUE TITLE
Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided."

### ISSUE THREAD

**Issue by ankit-meesho** [TanStack/virtual#557]
### Describe the bug

I am getting this error in my NextJs application.
Browser version : Chrome 60(OS: Android)
Opera version: 44.12 and 44.6(OS: Android)

Initialised it like this :
const rowVirtualizer = useWindowVirtualizer({
    count: batchedData.length,
    estimateSize: () => 500,
    enableSmoothScroll: true,
    overscan: 10,
 });

### Your minimal, reproducible example

NA

### Steps to reproduce

NA

### Expected behavior

NA

### How often does this bug happen?

Often

### Platform

Android: 6, 7
Browser version : Chrome 60(OS: Android)
Opera version: 44.12 and 44.6(OS: Android)

### tanstack-virtual version

3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tannerlinsley** [comment]
You need to flag your component as a client component with `use 'client'`
