### ISSUE TITLE
The div is trapped in endless loop and the slider is always jumping at certain position when I use Infinite Scroll

### ISSUE THREAD

**Issue by MJRT** [TanStack/virtual#567]
### Describe the bug

I'm trying to test Infinite Scroll example with my data, but it behavior is unexpected, the blow GIF should show a explicit case. It's trapped in endless loop and the slider is always jumping, but I can't find problem via debug info. I guess it may I wrongly use it or edge case problem.

### Your minimal, reproducible example

https://stackblitz.com/edit/stackblitz-starters-eldpph?file=src%2FApp.tsx

### Steps to reproduce

Just drag slider

### Expected behavior

normal display

### How often does this bug happen?

Every time

### Screenshots or Videos

![bugReproduce](https://github.com/TanStack/virtual/assets/17826582/bcf5f535-182b-4b6a-a7ab-af78c7b3f11c)

### Platform

OS: Linux
Browser: Chrome

### tanstack-virtual version

3.0.0-beta.54

### TypeScript version

5.1.6

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Symyon** [comment]
@MJRT have you found a solution for this or the cause of it? I have the same thing.

**Comment by Symyon** [comment]
Thanks @piecyk , it got rid of the issue above, but still have some jumping of the scrollbar when I scroll all the day down and keep it there. The biggest problem though now is that the scroll is jittery,  especially when it stops. Probably because it isn't "anchoring" now... I'll try to implement it in another way, have one of my scrolls working properly. Also I believe 'Alpha'  didn't  have this issue, might just downgrade to that  as well.

**Comment by Symyon** [comment]
Looks like the parent of the items need the height to be set, I using a tutorial/code from a V2 and implemented the changes for V3. Somewhere in there I lost that. So for the parent of the items:
 `height: `${rowVirtualizer.getTotalSize()}px`,`

**Comment by piecyk** [comment]
> Thanks @piecyk , it got rid of the issue above, but still have some jumping of the scrollbar when I scroll all the day down and keep it there. The biggest problem though now is that the scroll is jittery, especially when it stops.


That sound not right, it would mean that the height changes when you scroll down, are your rows dynamic? If they have different size from what you estimated, did you add `data-index` ref={`virtualizer.measureElement`} ?

> Probably because it isn't "anchoring" now... I'll try to implement it in another way, have one of my scrolls working properly. Also I believe 'Alpha' didn't have this issue, might just downgrade to that as well.

hmm don't quite understand what do you mean by anchoring, but we never had this feature.

**Comment by Symyon** [comment]
@piecyk fixed it, comment above. Thank you for your help!
