### ISSUE TITLE
Popover from antd creates lags on scrolling

### ISSUE THREAD

**Issue by sss1337xyz** [TanStack/virtual#575]
### Describe the bug

When I wrap an element in Popover from antd, I encounter that the scroll starts to lag.

In my real project this load seriously affects performance.

In the minimally reproduced example it is noticeable, but not much.

### Your minimal, reproducible example

https://codesandbox.io/s/headless-dream-wv8wxw

### Steps to reproduce

Wrap any virtualized element in Popover from Antd

https://codesandbox.io/s/headless-dream-wv8wxw

### Expected behavior

This was expected to have no impact on performance

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/TanStack/virtual/assets/41678172/fe3d1ba4-62d5-4591-b9c1-791da533b6ef

### Platform

windows 10
yandex browser

react-virtual beta 54 (and 56 in my local project)

### tanstack-virtual version

3.0.0-beta.54

### TypeScript version

4.7.4

### Additional context

Also I noticed that Link wrapper from react router dom also gives load and affects rendering.

To be honest, I don't know how to deal with it, except to write popover myself.

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@sss1337xyz it's happening as when scrolling the list is re-rendered to show what is visible, one option is to memo row https://codesandbox.io/s/happy-waterfall-q2zw7f?file=/src/App.jsss

**Comment by sss1337xyz** [comment]
> @sss1337xyz it's happening as when scrolling the list is re-rendered to show what is visible, one option is to memo row https://codesandbox.io/s/happy-waterfall-q2zw7f?file=/src/App.jsss



Thank you for your response. Yes indeed it gives a small performance boost.

But in my experience it does not give the same smoothness as if Popover was not there at all.

I just gave a very simple example with only 2 columns. In my real project there are 6 columns, and each column has Tooltip and Popover.
This kind of optimization doesn't help much there, but it helps.

**Comment by piecyk** [comment]
> I just gave a very simple example with only 2 columns. In my real project there are 6 columns, and each column has Tooltip and Popover.

Yep i agree, overall it's not an issue on virtual side but on impl of Popover/Tooltip

**Comment by sss1337xyz** [comment]
Since I think this will help someone, I'll leave feedback on how I came to a bit of a surprise.
1) Popover and Tooltip only load the dev build, on the production build it's as if it doesn't lose performance.

2) if there is still a desire to optimize this point, I would suggest a solution like this in your row
```
<div
          onMouseEnter={()=>setIsActivePopover(true)}
          onMouseLeave={()=>setIsActivePopover(false)}
>
        {isActivePopover ? (
            <Popover
                showHeader
                trigger="hover"
                title={'content'}
            >
              text
            </Popover>
        ) : (
            "text"
        )}
</div>
```

**Comment by soliyapintu** [comment]
@sss1337xyz When the user hovers over the popover content, it unexpectedly hides.

**Comment by piecyk** [comment]
@soliyapintu there is also isScrolling on instance, maybe you can use it to boost the performance.
