### ISSUE TITLE
rangeExtractor issue with flickering scroll

### ISSUE THREAD

**Issue by lkajtes-guru** [TanStack/virtual#583]
### Describe the bug

`"@tanstack/react-virtual": "^3.0.0-beta.60"`

I need to implement sticky section headers which are a part of data rows scrollable by users. While he scrolls, the section which is in the viewport needs to be sticky until all rows from that section end, then the next section header is sticky and so on...

I created a rangeExtractor function which I pass to `useVirtualizer` and it works fine until I reach the overscan threshold when the scroll starts to jump up/down. When I debug, I see that the first index after the sticky header index gets added and removed from the DOM, which triggers the scroll jumping and the `rangeExtractor` function is constantly executed with those start/end indexes being toggled. I could use some pointers on why this is happening. 

Below is a dulled down example of my code.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/reverent-satoshi-nlrr96?file=/src/main.tsx:75,89

### Steps to reproduce

Codesanbox shows the dulled down example of the code. If you start to scroll down and pass the overpass amount of rows, the scroll starts to shake

### Expected behavior

The inserted index of the sticky header should be added and the scroll not to shake

### How often does this bug happen?

Every time

### Platform

MacOS Ventura 13.4

### tanstack-virtual version

3.0.0-beta.60

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Checkout the sticky docs https://tanstack.com/virtual/v3/docs/examples/react/sticky like your example is missing position for rows, fyi if there is issue with flickering scroll try to disable https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor on parent.

**Comment by lkajtes-guru** [comment]
The anchor did stop the scroll flickering, but didn't solve the issue completely because indexes were being added/removed constantly. 

What did solve the issue is when I started following that example and being mindful of the row position and the ref of the parent I used for the useVirtualizer hook, so thanks for the help! :D
