### ISSUE TITLE
useWindowVirtualizer scrollToIndex locks scrolling position to bottom of the page

### ISSUE THREAD

**Issue by robojumper** [TanStack/virtual#589]
### Describe the bug

Our page uses `useWindowVirtualizer` and calls `virtualizer.scrollToIndex` when clicking entries in a "table of contents". We've upgraded from v3-beta.54 to v3-beta.60 and now when clicking any entry the window scrolls to the very bottom of the page. Scrolling up is not possible.

I've taken the `react/dynamic/RowVirtualizerDynamicWindow` example in codesandbox and added some buttons to call `scrollToIndex` to create a MCVE.

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/still-grass-vm62qd

### Steps to reproduce

1. Open the codesandbox
2. Click the "scroll to the middle" button

### Expected behavior

I expected the page to scroll to the middle of the list (around entry 5000), but instead the page scrolled to the very bottom. Attempting to scroll up doesn't work, the scroll position immediately snaps to the bottom again.

### How often does this bug happen?

Every time

### Platform

OS: Windows 10. Browsers: Edge 117, Firefox 117

### tanstack-virtual version

v3.0.0-beta.60

### Additional context

I suspect this is a side effect of PR #566.

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by mike667** [comment]
Have same issue, start with version v3.0.0-beta.57.
Rolled back in my application to v3.0.0-beta.56.

**Comment by piecyk** [comment]
@robojumper @mike667 should be fixed in latest beta 👍

**Comment by mike667** [comment]
@piecyk Thank you for your fix, but unfortunately it doesn't help me. I checked you changes and it help me solve my issue.

After adding this options all work perfect for me. Thank you.
initialOffset: 0,

If you interesting my research thoughts:
- I have long list. Press add button. Redirect user to add page.
- User fill add form, click add. React router redirect back to home page.
- Virtual table get old window.scrollY and save it to options, then react-router scroll restoration hook works and scroll window to the top (0,0). And Virtual table adjust scroll to old window.scrollY, and page become half scrolled.

But with initialOffset: 0, everything works ok:
- page scroll is on the top after adding form processed. (as I need)
- if you scroll to the item in the list, go to it's page and then click back on the browser arrow scroll still on the place where I was.

Unfortunately, I cannot create an example.

**Comment by piecyk** [comment]
@mike667 yes that is a different issue, but yes the initialOffset should be used when restoring scroll position.
