### ISSUE TITLE
Is it possible to use react-virtual in flexbox? 

### ISSUE THREAD

**Issue by skopz356** [TanStack/virtual#595]
### Describe the bug

When parentElement (return of getScrollElement) is in flexbox it expands parent element. Maybe this is intended behavior if it is I think that it should be stated in the docs. 

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/hopeful-silence-pggrx2?embed=1&file=%2Fsrc%2Fmain.tsx%3A6%2C19

### Steps to reproduce

Open the sandbox, the parent element with id "parent-ref" is overflowing its parent element. 

### Expected behavior

The parent element with id "parent-ref" should fill only available space, it should not expand its parent. 

### How often does this bug happen?

Every time

### Platform

- [Linux, Firefox, Chrome etc] I do not think that this issue is platform dependent. 

### tanstack-virtual version

3.0.0-beta.61

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@skopz356 yes it is, you need to set `min-width: 0` o flex item, checkout https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size/36247448#36247448

**Comment by mrlubos** [comment]
Hey @piecyk, does this package support `flex-wrap` too?
