### ISSUE TITLE
Breaking change: measureElement is not exposed anymore

### ISSUE THREAD

**Issue by GilHelfgottGong** [TanStack/virtual#610]
### Describe the bug

I've upgraded from version 3.0.0-beta.58 to version 3.0.0-beta.9 and using the dynamic approach as described in the documentation: https://tanstack.com/virtual/v3/docs/examples/react/dynamic
Since upgrading, the measureElement ref that's in line 84 in the link provided is undefined.
This causes miscalculation of the elements' height.
Thanks!

### Your minimal, reproducible example

https://tanstack.com/virtual/v3/docs/examples/react/dynamic

### Steps to reproduce

https://tanstack.com/virtual/v3/docs/examples/react/dynamic : line 84, measureElement is undefined

### Expected behavior

measureElement to work as in previous versions and measure the height of the elements.
Currently what I'm seeing is a mismatch between the actual height of the elements to the container size using getTotalSize()

### How often does this bug happen?

Every time

### Platform

OS: macOS
Browser: Chrome 118.0.5993.70

### tanstack-virtual version

3.0.0-beta.9

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@GilHelfgottGong there is small mismatch, latest version is [v3.0.0-beta.66](https://github.com/TanStack/virtual/releases/tag/v3.0.0-beta.66) till we sort it out you need to pin point the correct version.
