### ISSUE TITLE
react-virtual  v3.0.* is using strict version of virtual-core 3.0.0

### ISSUE THREAD

**Issue by karolzeluk** [TanStack/virtual#669]
### Describe the bug

All framework packages:
- `react-virual`
- `vue-virtual`
- `svelte-virtual`
- `solid-virtual`

in v3 releases has hardcoded version "3.0.0" of `virtual-core`

### Your minimal, reproducible example

https://github.com/TanStack/virtual/blob/v3.0.4/packages/react-virtual/package.json#L53

### Steps to reproduce

1. install react-virtual in version `3.0.4`
2. check the installed version of `virtual-core`
3. it is `3.0.0`

### Expected behavior

version of `virtual-core` should match version of `react-virtual` so it should be `3.0.4`

### How often does this bug happen?

None

### Platform

- macOS

### tanstack-virtual version

v3.0.4

### TypeScript version

v4.9.3

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
fixed via https://github.com/TanStack/virtual/pull/670
