### ISSUE TITLE
svelte-virtual: no release created since 3.0.4

### ISSUE THREAD

**Issue by stemcc** [TanStack/virtual#678]
### Describe the bug

Ever since [this commit](https://github.com/TanStack/virtual/commit/fd460bc4b5765d91ebfdb97fe0d29829392fbd84) by @piecyk and @lachlancollins there has not been a svelte-virtual release despite there being 3 releases since then. 

### Your minimal, reproducible example

n/a

### Steps to reproduce

No new svelte releases since 3.0.4

### Expected behavior

A svelte version along with all the other versions when a release is made.

### How often does this bug happen?

Every time

### Platform

- All 

### tanstack-virtual version

since 3.0.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by lachlancollins** [comment]
Fixed in #679
