### ISSUE TITLE
VirtualItem measurements are incorrect when getEstimateSize returns a string

### ISSUE THREAD

**Issue by Mr-Quin** [TanStack/virtual#695]
### Describe the bug

When getEstimateSize returns a string, e.g.
```js
  const rowVirtualizer = useVirtualizer({
    count: 10,
    getScrollElement: () => parentRef.current,
    estimateSize: () => '15',
    overscan: 5,
  })
```
the string gets concatenated, so the measurements look like
```js
// measurementsCache
[
    {
        "index": 0,
        "start": 0,
        "size": "15",
        "end": "015",
        "key": 0,
        "lane": 0
    },
    {
        "index": 1,
        "start": "0150",
        "size": "15",
        "end": "015015",
        "key": 1,
        "lane": 0
    },
    {
        "index": 2,
        "start": "0150150",
        "size": "15",
        "end": "015015015",
        "key": 2,
        "lane": 0
    },
    // ...etc
]
```

### Your minimal, reproducible example

https://codesandbox.io/p/devbox/new-wood-q9g2pn?file=%2Fsrc%2Fmain.jsx%3A45%2C1-50%2C5

### Steps to reproduce

The codesandbox is forked from the "fixed" example, modified to return a string in `estimateSize`.
The rows and columns are incorrectly spaced.

### Expected behavior

I expect it to not simply concatenate the string, maybe throw a runtime error

### How often does this bug happen?

Every time

### Platform

Chrome 123.0.6312.59

### tanstack-virtual version

v3.2.0

### Additional context

TypeScript may catch this at compile time, but we are using JS and in our use case the estimateSize is sourced from elsewhere and unknown until runtime, so this problem took quite some time to trace down.

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@Mr-Quin that is correct, size needs to be a number.
