### ISSUE TITLE
flushSync was called from inside a lifecycle method

### ISSUE THREAD

**Issue by fallenleavesguy** [TanStack/virtual#711]
### Describe the bug

![image](https://github.com/TanStack/virtual/assets/9261562/3a79c7f7-6794-476c-8a17-7a0b0d43b434)

demo:
[online demo](https://stackblitz.com/edit/tanstack-virtual-8k7f6g?file=src%2Fh-infinite-scroll.tsx)

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-virtual-8k7f6g?file=package.json

### Steps to reproduce

https://stackblitz.com/edit/tanstack-virtual-8k7f6g?file=src%2Fh-infinite-scroll.tsx

### Expected behavior

no warning

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://github.com/TanStack/virtual/assets/9261562/e6ee6eb7-6749-441c-a62f-e3874c936811)

### Platform

all platform

### tanstack-virtual version

v3.30.0

### TypeScript version

v5.2.2

### Additional context

custom observeElementOffset to fixed over scroll bouncing bug below ios 16

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
@fallenleavesguy there is an error in example 

>  ✘ [ERROR] Unexpected "}"

regardless the flushSync error is connected to your custom observeElementOffset, the issue is that when calling `handler` in initial call then isScrolling should be false as you are not really scrolling in that time in context of virtualizer, when isScrolling is true react adapter will use flushSync to limit the rendering lag.

**Comment by fallenleavesguy** [comment]
> @fallenleavesguy there is an error in example
> 
> > ✘ [ERROR] Unexpected "}"
> 
> regardless the flushSync error is connected to your custom observeElementOffset, the issue is that when calling `handler` in initial call then isScrolling should be false as you are not really scrolling in that time in context of virtualizer, when isScrolling is true react adapter will use flushSync to limit the rendering lag.

yet, sorry and thank you for your reply, there are many error in my example. I just for official example.And I can't find any way to fix tsx error in official example project.
Is there any problem? if I just ignore the flushSync warning.There is strange animation(scrollTop became zero suddenly) when scrolling on the edge below ios 16(because something causes reflow when scrolling on the edge).So I have to use observeElementOffset, and only call cb callback between 0 and scrollWidth - clientWidth

**Comment by fallenleavesguy** [comment]
@piecyk thank you guy.I have fixed types errors in my example project.You could check it out.

**Comment by piecyk** [comment]
@fallenleavesguy you can also use default observeElementOffset and tweak the offset like this  

```js
const columnVirtualizer = useVirtualizer({
  horizontal: true,
  count,
  getScrollElement: () => parentRef.current,
  estimateSize: () => 100,
  overscan: 6,
  observeElementOffset: (instance, cb) =>
    observeElementOffset(instance, (offset, isScrolling) =>
      cb(
        Math.max(
          0,
          Math.min(
            offset,
            instance.options.horizontal
              ? instance.scrollElement!.scrollWidth -
                  instance.scrollElement!.clientWidth
              : instance.scrollElement!.scrollHeight -
                  instance.scrollElement!.clientHeight
          )
        ),
        isScrolling
      )
    ),
});
```

https://stackblitz.com/edit/tanstack-virtual-qyuryg?file=src%2Fh-infinite-scroll.tsx

**Comment by fallenleavesguy** [comment]
> @fallenleavesguy you can also use default observeElementOffset and tweak the offset like this
> 
> ```js
> const columnVirtualizer = useVirtualizer({
>   horizontal: true,
>   count,
>   getScrollElement: () => parentRef.current,
>   estimateSize: () => 100,
>   overscan: 6,
>   observeElementOffset: (instance, cb) =>
>     observeElementOffset(instance, (offset, isScrolling) =>
>       cb(
>         Math.max(
>           0,
>           Math.min(
>             offset,
>             instance.options.horizontal
>               ? instance.scrollElement!.scrollWidth -
>                   instance.scrollElement!.clientWidth
>               : instance.scrollElement!.scrollHeight -
>                   instance.scrollElement!.clientHeight
>           )
>         ),
>         isScrolling
>       )
>     ),
> });
> ```
> 
> https://stackblitz.com/edit/tanstack-virtual-qyuryg?file=src%2Fh-infinite-scroll.tsx

Works very Well below ios 16.The snippet may add to virtual hook codebase to awoid bug below ios 16
