### ISSUE TITLE
Not working using separated wrapper component

### ISSUE THREAD

**Issue by kykim00** [TanStack/virtual#735]
### Describe the bug

this is part of the code used in the dynamic example. 

```
<div
  style={{
    position: "relative",
    height: virtualizer.getTotalSize(),
  }}
>
  <div
    style={{
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      transform: `translateY(${items[0]?.start ?? 0}px)`,
    }}
  >
    {items.map( .... )}
  </div>
 </div>
```

it doesn't work if separate the div wrapper into components.

```
<Wrapper height={virtualizer.getTotalSize()} start={items[0]?.start ?? 0}>
  {items.map( .. )}
</Wrapper>

const Wrapper = ({ height, start, children }) => (
  <div style={{ position: "relative", height: height }}>
    <div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        transform: `translateY(${start}}px)`,
      }}
    >
      {children}
    </div>
  </div>
);
```

how can I fix it?

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/tanstack-virtual-9x5xkf?file=%2Fsrc%2FApp.js%3A76%2C3

### Steps to reproduce

1. open codesandbox https://codesandbox.io/p/sandbox/tanstack-virtual-9x5xkf?file=%2Fsrc%2FApp.js%3A76%2C3
2. click 'open' button
3. scroll

### Expected behavior

only few items located in the front can be seen

### How often does this bug happen?

Every time

### Platform

mac OS
Chrome 125.0.6422.76

### tanstack-virtual version

v3.5.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
I think the issue is with conditional rendering the list, store containerRef on state, like  

```
const [container, setContainer] = useState(null);
```
and then 
```
getScrollElement: () => container,
```

**Comment by kykim00** [comment]
If I remove the conditional rendering part and store containerRef on state, the same issue continues.

**Comment by piecyk** [comment]
@kykim00 there is typo in Wrapper styles it should be

```
style={{
  position: "absolute",
  top: 0,
  left: 0,
  width: "100%",
  transform: `translateY(${start}px)`,
}}
```
