### ISSUE TITLE
@tanstack/lit-virtual is missing a README

### ISSUE THREAD

**Issue by justinfagnani** [TanStack/virtual#762]
### Describe the bug

@tanstack/lit-virtual package is missing a README which makes the npmjs.com page (and other registries) much less useful than it could be.

See https://www.npmjs.com/package/@tanstack/lit-virtual

<img width="1146" alt="Screenshot 2024-07-13 at 5 10 59 PM" src="https://github.com/user-attachments/assets/9d8231fc-692b-42e2-b321-80459552c5d5">

npmjs.com packages tend to rank very highly on search results. Without a README it's difficult to tell what a package is about, and maybe a reader never makes it to the official docs site. Even something minimal that describes the package and links to docs would be helpful.

### Your minimal, reproducible example

n/a

### Steps to reproduce

Go to https://www.npmjs.com/package/@tanstack/lit-virtual

### Expected behavior

See some README content

### How often does this bug happen?

Every time

### Platform

n/a

### tanstack-virtual version

n/a

### TypeScript version

n/a

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by kadoshms** [comment]
Added a Readme which we can start from: 
https://github.com/TanStack/virtual/pull/766
