### ISSUE TITLE
items missing from elementsCache when using getItemKey to set a unique memoizable key

### ISSUE THREAD

**Issue by fridaystreet** [TanStack/virtual#794]
### Describe the bug

We've finally managed to get an infinite scroll working and have the scrollToIndex working nicely after more data is fetched. Up to now we have just been using row.key for the row's key and it is just using the index number, we have no getItemKey fn.

Our scroll is a reverse scroll type for a chat thread and we are getting a lot of rerendering, as obviously with data always coming into the top of the list when scrolling back for old messages, the position of each message is changing and causing the rerender. So we wanted to use getItemKey to set the key to the message.id

When we try and set the getItemKey fn, when trying to set scrollToIndex after the data fetch, it can't find the previously scrolled to item in the elementCache and it just goes into an infinite loop trying to (

### Your minimal, reproducible example

none

### Steps to reproduce

see below from the libraries scrollToIndex fn)

```javascript
this.scrollToIndex = (index, { align: initialAlign = "auto", behavior } = {}) => {
      index = Math.max(0, Math.min(index, this.options.count - 1));
      this.cancelScrollToIndex();
      if (behavior === "smooth" && this.isDynamicMode()) {
        console.warn(
          "The `smooth` scroll behavior is not fully supported with dynamic size."
        );
      }
      const offsetAndAlign = this.getOffsetForIndex(index, initialAlign);
      if (!offsetAndAlign) return;
      const [offset, align] = offsetAndAlign;
      this._scrollToOffset(offset, { adjustments: void 0, behavior });
      if (behavior !== "smooth" && this.isDynamicMode() && this.targetWindow) {
        this.scrollToIndexTimeoutId = this.targetWindow.setTimeout(() => {
          this.scrollToIndexTimeoutId = null;
          const elementInDOM = this.elementsCache.has(
            this.options.getItemKey(index)
          );
          if (elementInDOM) {
            const [latestOffset] = notUndefined(
              this.getOffsetForIndex(index, align)
            );
            if (!approxEqual(latestOffset, this.getScrollOffset())) {
              this.scrollToIndex(index, { align, behavior });
            }
          } else {
            this.scrollToIndex(index, { align, behavior });
          }
        });
      }
    };
 ```

this part 
```javascript
const elementInDOM = this.elementsCache.has(
            this.options.getItemKey(index)
          );
```

it finds the key from the item no problem, but then can't find the key in the cache, so elementInDOM is always false and so it keeps recalling itself

```javascript
if (elementInDOM) {
            ...
          } else {
            this.scrollToIndex(index, { align, behavior }); //just calls this over and over
          }
```

If we inspect the elementsCache through the loading process from loading the first page, then the subsequent next page after scrolling back to fetch next. it appears that when using the unique key, some rows are missing from the cache. for example we have 50 message. We load 30 messages on initial mount. on scroll back, we fetch the last 20.

When using just the index number, the cache updates and shows, 30, then shows 50 and our call to scrollToIndex works perfectly and sets the scroll to the correct position.

When we try and use getItemKey and set a unique key that never changes between renders/mounts etc. The element cache locads the first 30, then after the next fetch it only has 38 items.

this is a cut down version of our scroll component

```javascript
export const InfiniteScroll = React.memo(({
  children,
  next,
  hasMore,
  loading,
  scrollableTarget,
  estimateSize=1,
  overscan=50,
  fixedRowCount=0,
  pageSize=30
}) => {


  const topRef = useRef()
  const bottomRef = useRef()
  const scrollRef = useRef()
  const initialScrolledToIndexRef = useRef()
  const lastScrollSizeRef = useRef()
  const lastDataLength = useRef(0)
  const lastScrollRef = useRef()

  const initialLoadComplete = useMemo(() => {
    return children.length > fixedRowCount && children.length <= pageSize + fixedRowCount
  }, [children.length, fixedRowCount, pageSize])

  useEffect(() => {
    if (children.length <= fixedRowCount && lastDataLength.current) {
      lastDataLength.current = 0
      scrollRef.current = undefined
      lastScrollRef.current = undefined
      lastScrollSizeRef.current = undefined
      initialScrolledToIndexRef.current = undefined
    }
  }, [children.length, lastDataLength])

  const onChange = useCallback(instance => {
      const size = instance.getTotalSize()
      const lastSize = lastScrollSizeRef.current || size
      lastScrollSizeRef.current = size

      if (lastSize < size) {
        if (!scrollRef.current) {

          if (!lastScrollRef.current) {
            if (!initialLoadComplete) return
            const index = typeof initialScrolledToIndexRef.current === 'number' ? initialScrolledToIndexRef.current : instance.measurementsCache.length-1

            initialScrolledToIndexRef.current = index
            console.log('scrollToBottomOnLoad', index)
            instance.scrollToIndex(index, { align: 'end' })
            return
          }
          const key = instance.options.getItemKey(lastScrollRef.current.index)
          console.log('findKey', key)
          if (!instance.elementsCache.has(key)) return

          console.log('scrollafterdata', lastScrollRef.current.index)
          instance.scrollToIndex(lastScrollRef.current.index, { align: 'start' })
          return
        }

        if (lastDataLength.current < children.length) {
          lastScrollRef.current = {
            ...scrollRef.current,
            index: scrollRef.current.index + (children.length - lastDataLength.current)
          }
          lastDataLength.current = children.length
          scrollRef.current =  undefined
        }
      }
  }, [lastScrollSizeRef, scrollRef, lastScrollRef, initialLoadComplete, initialScrolledToIndexRef, lastDataLength, children])

  const rangeExtractor = useCallback(range => {
    const initialIndex = initialScrolledToIndexRef.current
    if (scrollRef.current || (typeof initialIndex === 'number' && initialIndex > range.endIndex)) {
      scrollRef.current = {
        index: range.startIndex
      }
    }
    return defaultRangeExtractor(range)
  }, [virtualizer, initialScrolledToIndexRef, scrollRef, children.length, lastDataLength, lastScrollRef])

  const getScrollElement = useCallback(() => {
    return scrollableTarget.current
  }, [scrollableTarget])

  const getEstimateSize = useCallback(() => {
    return estimateSize ? typeof estimateSize === 'function' ? estimateSize() : typeof estimateSize === 'number' ? estimateSize : 1 : 1
  }, [estimateSize])

  const getItemKey = useCallback(index => {
    const child = children[index]
    if (!child.key) return index
    return child.key
  }, [children])

  const virtualizer = useVirtualizer({
    count: children.length,
    getScrollElement,
    estimateSize: getEstimateSize,
    overscan,
    onChange,
    rangeExtractor,
    getItemKey
  })

  const canGetMore = useCallback(() => {
    return  hasMore && !loading && lastDataLength.current && scrollRef.current
  }, [hasMore, loading, lastDataLength, scrollRef])

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          if ('top' === entry.target.id) && canGetMore()) {
            next()
          }
        }
      });
    });

    if (topRef.current) {
      observer.observe(topRef.current)
    }

    return () => {
      observer.disconnect()
    };
  }, [next, topRef, canGetMore])

  return (
    <div
      style={{
        height: '100%',
        width: "100%",
        position: "relative",
      }}
    >
      <div id="top" ref={topRef} />
        {virtualizer.getVirtualItems().map(virtualRow => (
          <div
            key={virtualRow.key}
            data-index={virtualRow.index}
            ref={virtualRow.measureElement}
          >
            {children[virtualRow.index]}
          </div>
        ))}
    </div>
  )
})
```

and an example of calling it. Our feed list has some fixed components like a list suffix so fixedRowCount allows that to be accounted for in the calculations on scroll Position.

```javascript
<InfiniteScroll
   next={getNext}
   hasMore={hasMore}
   loading={loading}
   scrollableTarget={scrollRef}
   fixedRowCount={1}
   pageSize={30}
>
  {feedList}
</InfiniteScroll>
```

### Expected behavior

the elementsCache should hold all the items even with unique keys. Probably also needs a retry count or something so that if it doesn't exists it doesn't just infinitely loop

### How often does this bug happen?

Every time

### Screenshots or Videos

none

### Platform

chrome, macso, react 18

### tanstack-virtual version

v3.8.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fridaystreet** [comment]
OK so we've done a bit more digging on this for some reason when you use getItemKey the elementCache size is not expanding. Not sure if that makes any sense to anyone.

In the below, even though children.length is bigger (and all the items render) elementsCache is only 30 (in our case). If I manually set count to 500, the cache allows all the 50 items in it no problem. 

At first I thought it was just not updating once the virtualiser had been initialised, ie so it was getting set to the first value of children.length when the component mounted, but that can't be the case as when it first mounts, children.length is 1. 

Plus I don't even know why it's using 30. The first full load of data has children.length = 31 as there is a suffix item after the list items 

```javascript
const virtualizer = useVirtualizer({
    count: children.length,
    scrollPaddingStart,
    scrollPaddingEnd,
    getScrollElement,
    estimateSize: getEstimateSize,
    overscan,
    onChange,
    rangeExtractor,
    getItemKey
  })
```

Am I completely missing something here?

Cheers

**Comment by piecyk** [comment]
> OK so we've done a bit more digging on this for some reason when you use getItemKey the elementCache size is not expanding. Not sure if that makes any sense to anyone.

That is true, elementCache only holds node rendered into DOM.

> When we try and set the getItemKey fn, when trying to set scrollToIndex after the data fetch, it can't find the previously scrolled to item in the elementCache and it just goes into an infinite loop trying to

That would mean it didn't scroll to that place and row under that key was not rendered. You can check `measurementsCache` on virtualizer instance if data looks right after load more, also where we are via scrollOffset etc.

If it still is not working, create small example and can check it.

**Comment by fridaystreet** [comment]
apologies I don't have a working sandbox, I'll try extracting the code into a standalone example on the weekend, I've managed to modulise it now. This is basically the last remaining issue. Well guess it's not a huge issue, but it would be nice to not have the list fully rerender everytime.

In the meantime here is a video that hopefully may help. As you can see, it fetches 30 items. The premise here is that onload it wants to set the scroll to the bottom (reverse list for chat). When you scroll back (infinite scrolle) to fetch the next  30, it scrolls you back to the lat item that was in view at the time you scrolled back

So basically that equates to

1. load 30 items
2. scrollToIndex 29 end , ie the bottom
3. scroll back to index 0 (the top) save the scroll position 0
4. fetch the next 30 (this might be 15, but let's just stick with another 30 for simplicity)
5. prepend them to the list
6. now add the length of the newley fetched items to the previous index 0+30-1 (minus 1 for the actual array index)
7. We use the OnChange function to check if the total size has changed and wait for the last fire of onChange, by checking if elementsCache is the same size as items.length. Once it is, we know we are at the last reszie event. 
8. so then we can do scrollToIndex because everything shoudl be rendered to its full size
9. so if this is not the initial load, we are scrollToIndex(29, { align: 'start'}). 0, which is now index 29 was at the top before we fetched the data, so make sure we're back where we were after the data has been added

So in the video you can see from the logging, we run the log on every onChange event that is a resize. Once it is the last resize, we scroll to bottom. Then we fetch next 30, but it never gets to the last resize event, because as you can se in the logs, elementsCahce never gets past 30, while items.length and measurementsCache both have the full list of 60 items


https://github.com/user-attachments/assets/00081d51-e7aa-4f26-a673-a7449fe62404

**Comment by fridaystreet** [comment]
Sorry just thought I'd make a video showing it with getItemKey disabled. So it's exactly same code, same data, just using the array index. As you can see, after the scroll back and fetch of the second 30 items, it scrolls back to the original mesaage position that was at the top of the scroll before the fetch as designed.

https://github.com/user-attachments/assets/2522c0bf-9548-4098-9035-181b3221f746

**Comment by fridaystreet** [comment]
could it be that elementsCache doesn't actually hold all of the rendered items, only the last rendered items? 

By that I mean, the first time it loads, it gets 30 items, they get rendered, elementsCache contains 30. On the next fetch, the previous items (now with stable keys) aren't rerendered, so they aren't added to elementsCache? So elementsCache when using stable keys will only ever be the size of the new unrendered items?

Seems a bit weird if that is the case as not having the element in the cache causes the original issue where the following code inside scrollToIndex cacn't find the item and keeps looping

```javascript

const elementInDOM = this.elementsCache.has(
            this.options.getItemKey(index)
          );
          if (elementInDOM) {
            const [latestOffset] = notUndefined(
              this.getOffsetForIndex(index, align)
            );
            if (!approxEqual(latestOffset, this.getScrollOffset())) {
              this.scrollToIndex(index, { align, behavior });
            }
          } else {
            this.scrollToIndex(index, { align, behavior });
          }
```

**Comment by piecyk** [comment]
> could it be that elementsCache doesn't actually hold all of the rendered items, only the last rendered items?

yep, elementsCache only holds items current rendered, so if you have 0,1,2 then scroll down to 10, nodes for 0,1,2 will be removed from cache. 

Thinking on it now, could be some race condition with current elements and new after fetch, 

Looks like you are using the measureElement from item like `ref={virtualRow.measureElement}`, what would happen if you will change it to pass from virtualizer `ref={virtualizer.measureElement}`

**Comment by piecyk** [comment]
So this is measureElement method on item https://github.com/TanStack/virtual/blob/main/packages/virtual-core/src/index.ts#L621-L648 as you can see,

**Comment by fridaystreet** [comment]
I'll try out the measurement thing, but 

> yep, elementsCache only holds items current rendered, so if you have 0,1,2 then scroll down to 10, nodes for 0,1,2 will be removed from cache.

If what you're saying holds regarding things getting dropped out of the cache on scroll, then a couple of things don't seem right. I don't think this is the case, or maybe I'm misundarstanding what you mean? 

1) As you can see from the second video, elementsCache is always the same size as measurementsCache once any resizing has finished. It doesn't matter if I scroll things in or out of view, elementsCache doesn't change once it's all rendered, unless something changes the size and it gets recalculated. 
2) All items in this case are rendered as the overscan is double the list length.

**Comment by fridaystreet** [comment]
OK using virtualizer.measureElement has fixed it. Thankyou for your help and patience.

Apologies though for hopefully not wasting too much of your time. And now I feel a bit foolish as I've just check the documentation/examples and that's what is used. No doubt I had that in there when I first started and just thorugh dev process of refactoring things once we got it working how we wanted, I've inadvertantly just thought those 3 props in the items surrounding div were all reading off virtualRow :-(

This is working
```javascript
return virtualizer.getVirtualItems().map(virtualRow => {
    const { RenderItem, ...props } = items[virtualRow.index]
    return <div
      key={virtualRow.key}
      data-index={virtualRow.index}
      ref={virtualizer.measureElement}
    >
       <RenderItem {...props} />
    </div>
  })

```

**Comment by fridaystreet** [comment]
Once I get it finished and tested I'll share the full code. It's a pretty extensive bi-directional infinite scroll with user scroll detetection vs programatic scroll and has perfect (now it doesn't rerender lol) re-position of scroll after fetch of more data, auto reposition on new data and can take a dynamic index to position to (ie scroll to last unread) and handles dynamic sized items no problem. I couldn't actually find a full code example or library of a fully working infinite scroll for chat hence we started to piece together the examples and came up with this.

So hopefully it can be of use to someone and provide some input back into the community.

Thanks again for your help

**Comment by piecyk** [comment]
> OK using virtualizer.measureElement has fixed it.

Awesome  

> Apologies though for hopefully not wasting too much of your time. And now I feel a bit foolish as I've just check the documentation/examples and that's what is used. 

Clearly we have a bug somewhere, the measureElement should work the same, regardless if we use instance method or one on the item

> Once I get it finished and tested I'll share the full code.

That would be great 👍

**Comment by fridaystreet** [comment]
Do you want me to close this @piecyk or are you leaving it open to work out that bug?

**Comment by piecyk** [comment]
Fixed by https://github.com/TanStack/virtual/pull/801

**Comment by fridaystreet** [comment]
nice one :-)
