### ISSUE TITLE
Failing tanstack/virtual-core build on NPM (version 3.10.0)

### ISSUE THREAD

**Issue by kbrgl** [TanStack/virtual#804]
### Describe the bug

bun add v1.1.12 (43f0913c)
error: No version matching "3.10.0" found for specifier "@tanstack/virtual-core" (but package exists)

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Try to install @tanstack/virtual-core using bun or another package manager.

### Expected behavior

I expected the install to succeed but it failed with an error message

### How often does this bug happen?

Every time

### Platform

macOS

### tanstack-virtual version

v3.10.0

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by rileyjshaw** [comment]
I’m seeing this too when trying to install `@headlessui/react`; I think all packages depending on `@tanstack/virtual-core` won’t be installable until the registry version is fixed.

In the meantime, folks can get unblocked by adding the following to `package.json`:

```
	"overrides": {
		"@tanstack/react-virtual": "3.9.0"
	},
```

**Comment by CChenelFlo** [comment]
yep, for me it fails there : 

silly placeDep node_modules/@asyncapi/cli/node_modules/@asyncapi/studio/node_modules/@tanstack/react-virtual @tanstack/virtual-core@ OK for: @tanstack/react-virtual@3.10.0 want: 3.10.0

Seems to try to access 3.10.0 of @tanstack/virtual-core but latest release is 3.9.0 :

https://www.npmjs.com/package/@tanstack/virtual-core

![image](https://github.com/user-attachments/assets/7aa359d5-02bc-4c1a-86ef-478cb337d580)

3899 verbose stack @tanstack/virtual-core: No matching version found for @tanstack/virtual-core@3.10.0.
3899 verbose stack     at module.exports (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
3899 verbose stack     at RegistryFetcher.manifest (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/npm/node_modules/pacote/lib/registry.js:131:54)

**Comment by rileyjshaw** [comment]
@piecyk calling your attention to this (another comment [here](https://github.com/TanStack/virtual/commit/a873595f9945a035b777191ddb9c49d0b4e492e9#commitcomment-145531592) since it seems like a pretty severe issue.

**Comment by piecyk** [comment]
Yes, sorry for the hassle, our auto publish script gone south. @tannerlinsley need to fix it manually.

**Comment by BoogerKlown** [comment]
@piecyk Looking into it, it seems to be related to the angular-virtual package.  Its not on NPM and seems like the last attempt to publish that package had some issues when I review the git history.  Hope that information helps.

**Comment by Layouwen** [comment]
You can first specify the version `4.9.0` and then remove it after subsequent fixes.
```bash
pnpm i -D @tanstack/react-virtual@3.9.0
```

**Comment by piecyk** [comment]
Fixed
