### ISSUE TITLE
Not resizing all virtuals elements

### ISSUE THREAD

**Issue by RSelwa** [TanStack/virtual#894]
### Describe the bug

When we resize the width of the container, the height of all the images changes. It changes the images that are rendered width getVirtualsItems indeed BUT it doesn't change the images that are been loaded before so when we're going backwards. All the previous images are resized when re-rendered so it cause a big flickering in the grid. Is there a way to resize all the images that are previously rendered ? Maybe with resizeItem but it doesn't seems to work.
Thanks in adavance

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/6fn4mk

### Steps to reproduce

Scroll a bit, click on the "change height" button, one or twice then scroll back, you will see all the flickering happens

### Expected behavior

When we resize the width of the container, we should resize ALL the images and not only the one which are rendered with virtualizer.getVirtualItems. 

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/user-attachments/assets/e27eaa53-b75e-402e-a147-7bdfd6a4d070

### Platform

Windows & Mac 
Chrome  

### tanstack-virtual version

v3.10.8

### TypeScript version

v5.5.3

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment]
Hi @RSelwa, when getItemKey will change then virtual items will be re-created, so that's why it's good to keep it stale wrapping it with useCallback, like `getItemKey: useCallback((index: number) => index, [height]),` 

also virtual item you had fixed height, that was not reflecting what we have in items, `height: img.size,` 

checkout the https://codesandbox.io/p/sandbox/tanstack-virtual-forked-gcrmjc

**Comment by RSelwa** [comment]
Okay, I see, the img.size resolve it, thank you for your help 🙏🏼

**Comment by RSelwa** [comment]
What if we're resizing our number of columns, the column width gonna be larger but the size isn't increasing automatically to keep the ratio
