### ISSUE TITLE
bug: getTotalSize result is wrong when using dynamic height with unique react key

### ISSUE THREAD

**Issue by jiwon79** [TanStack/virtual#896]
### Describe the bug

getTotalSize result is wrong when using dynamic height with unique react key

### Your minimal, reproducible example

Stackblitz

### Steps to reproduce

1. https://stackblitz.com/edit/vitejs-vite-6ga1qf2e?file=src%2FApp.tsx
2. right border show getTotalSize height
3. input "fe"
4. right border is diff with content height

### Expected behavior

right black border height is same with content height

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/user-attachments/assets/2989fe71-0180-428e-a5f1-df639f0b82dc

### Platform

macOS, chrome

### tanstack-virtual version

v3.11.0

### TypeScript version

~5.6.2

### it's show wrong total size
```tsx
<div
  key={filteredSentences[virtualRow.index]}
  data-index={virtualRow.index}
  ref={virtualizer.measureElement}
>
```

### it's show correct total size
```tsx
<div
  key={filteredSentences[virtualRow.index]}
  data-index={virtualRow.index}
  ref={(ref) => virtualizer.measureElement(ref)}
>
```
```tsx
<div
  key={virtualRow.index}
  data-index={virtualRow.index}
  ref={virtualizer.measureElement}
>
```
```tsx
<div
  key={filteredSentences[virtualRow.index]}
  data-index={virtualRow.index}
  ref={(ref) => virtualizer.measureElement(ref)}
>
```
```tsx
<div
  data-index={virtualRow.index}
  ref={virtualizer.measureElement}
>
```

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by jiwon79** [comment]
I dig into the bug. It cause by react callback ref action.
```tsx
// 1. pass direct
ref={instance.measure}
// 2. pass ref by param
ref={(ref) => instance.measure(ref)}
```
when 5 items to 2 items by filter, 1) measure function pass "null, null, null" 2) measure function pass "null, null, null, null, null, DOM node, DOM node"

If you think it is not bug, you can close this issue.

**Comment by piecyk** [comment]
You can use arrow for ref but it would be a little slower, some hints 

* getItemKey need to be stale, as it based on it value virtual is invalidating array of item positions, `getItemKey: React.useCallback((index: number) => filteredSentences[index], [])`   
* use virtualRow.key if need to pass a key

https://stackblitz.com/edit/vitejs-vite-6ga1qf2e?file=src%2FApp.tsx
